// Copyright (c) 2026 Framlux LLC
// Licensed under the MIT License
// See LICENSE for details.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: AgentRegistration.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registration_GetRegistrationStatus_FullMethodName = "/agent.Registration/GetRegistrationStatus"
	Registration_RegisterSystem_FullMethodName        = "/agent.Registration/RegisterSystem"
)

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrationClient interface {
	GetRegistrationStatus(ctx context.Context, in *SystemRegistrationStatusRequest, opts ...grpc.CallOption) (*SystemRegistrationStatusResponse, error)
	RegisterSystem(ctx context.Context, in *RegisterSystemRequest, opts ...grpc.CallOption) (*RegisterSystemResponse, error)
}

type registrationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationClient(cc grpc.ClientConnInterface) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) GetRegistrationStatus(ctx context.Context, in *SystemRegistrationStatusRequest, opts ...grpc.CallOption) (*SystemRegistrationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemRegistrationStatusResponse)
	err := c.cc.Invoke(ctx, Registration_GetRegistrationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) RegisterSystem(ctx context.Context, in *RegisterSystemRequest, opts ...grpc.CallOption) (*RegisterSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSystemResponse)
	err := c.cc.Invoke(ctx, Registration_RegisterSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
// All implementations must embed UnimplementedRegistrationServer
// for forward compatibility.
type RegistrationServer interface {
	GetRegistrationStatus(context.Context, *SystemRegistrationStatusRequest) (*SystemRegistrationStatusResponse, error)
	RegisterSystem(context.Context, *RegisterSystemRequest) (*RegisterSystemResponse, error)
	mustEmbedUnimplementedRegistrationServer()
}

// UnimplementedRegistrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServer struct{}

func (UnimplementedRegistrationServer) GetRegistrationStatus(context.Context, *SystemRegistrationStatusRequest) (*SystemRegistrationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistrationStatus not implemented")
}
func (UnimplementedRegistrationServer) RegisterSystem(context.Context, *RegisterSystemRequest) (*RegisterSystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSystem not implemented")
}
func (UnimplementedRegistrationServer) mustEmbedUnimplementedRegistrationServer() {}
func (UnimplementedRegistrationServer) testEmbeddedByValue()                      {}

// UnsafeRegistrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServer will
// result in compilation errors.
type UnsafeRegistrationServer interface {
	mustEmbedUnimplementedRegistrationServer()
}

func RegisterRegistrationServer(s grpc.ServiceRegistrar, srv RegistrationServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registration_ServiceDesc, srv)
}

func _Registration_GetRegistrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemRegistrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).GetRegistrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_GetRegistrationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).GetRegistrationStatus(ctx, req.(*SystemRegistrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_RegisterSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).RegisterSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_RegisterSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).RegisterSystem(ctx, req.(*RegisterSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registration_ServiceDesc is the grpc.ServiceDesc for Registration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegistrationStatus",
			Handler:    _Registration_GetRegistrationStatus_Handler,
		},
		{
			MethodName: "RegisterSystem",
			Handler:    _Registration_RegisterSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AgentRegistration.proto",
}
