// Copyright (c) 2026 Framlux LLC
// Licensed under the MIT License
// See LICENSE for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: AgentRegistration.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationStatus int32

const (
	RegistrationStatus_UNKNOWN_REGISTRATION RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_ACTIVE  RegistrationStatus = 1
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "UNKNOWN_REGISTRATION",
		1: "REGISTRATION_ACTIVE",
	}
	RegistrationStatus_value = map[string]int32{
		"UNKNOWN_REGISTRATION": 0,
		"REGISTRATION_ACTIVE":  1,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_AgentRegistration_proto_enumTypes[0].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_AgentRegistration_proto_enumTypes[0]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{0}
}

type MachineType int32

const (
	MachineType_UNKNOWN_TYPE           MachineType = 0
	MachineType_DESKTOP_TYPE           MachineType = 1
	MachineType_LAPTOP_TYPE            MachineType = 2
	MachineType_BARE_METAL_SERVER_TYPE MachineType = 3
	MachineType_VIRTUAL_MACHINE_TYPE   MachineType = 4
)

// Enum value maps for MachineType.
var (
	MachineType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "DESKTOP_TYPE",
		2: "LAPTOP_TYPE",
		3: "BARE_METAL_SERVER_TYPE",
		4: "VIRTUAL_MACHINE_TYPE",
	}
	MachineType_value = map[string]int32{
		"UNKNOWN_TYPE":           0,
		"DESKTOP_TYPE":           1,
		"LAPTOP_TYPE":            2,
		"BARE_METAL_SERVER_TYPE": 3,
		"VIRTUAL_MACHINE_TYPE":   4,
	}
)

func (x MachineType) Enum() *MachineType {
	p := new(MachineType)
	*p = x
	return p
}

func (x MachineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineType) Descriptor() protoreflect.EnumDescriptor {
	return file_AgentRegistration_proto_enumTypes[1].Descriptor()
}

func (MachineType) Type() protoreflect.EnumType {
	return &file_AgentRegistration_proto_enumTypes[1]
}

func (x MachineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineType.Descriptor instead.
func (MachineType) EnumDescriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{1}
}

type OperatingSystemType int32

const (
	OperatingSystemType_UNKNOWN_OS OperatingSystemType = 0
	OperatingSystemType_WINDOWS_OS OperatingSystemType = 1
	OperatingSystemType_MAC_OS     OperatingSystemType = 2
	OperatingSystemType_UBUNTU_OS  OperatingSystemType = 3
	OperatingSystemType_FEDORA_OS  OperatingSystemType = 4
	OperatingSystemType_REDHAT_OS  OperatingSystemType = 5
	OperatingSystemType_DEBIAN_OS  OperatingSystemType = 6
)

// Enum value maps for OperatingSystemType.
var (
	OperatingSystemType_name = map[int32]string{
		0: "UNKNOWN_OS",
		1: "WINDOWS_OS",
		2: "MAC_OS",
		3: "UBUNTU_OS",
		4: "FEDORA_OS",
		5: "REDHAT_OS",
		6: "DEBIAN_OS",
	}
	OperatingSystemType_value = map[string]int32{
		"UNKNOWN_OS": 0,
		"WINDOWS_OS": 1,
		"MAC_OS":     2,
		"UBUNTU_OS":  3,
		"FEDORA_OS":  4,
		"REDHAT_OS":  5,
		"DEBIAN_OS":  6,
	}
)

func (x OperatingSystemType) Enum() *OperatingSystemType {
	p := new(OperatingSystemType)
	*p = x
	return p
}

func (x OperatingSystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatingSystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_AgentRegistration_proto_enumTypes[2].Descriptor()
}

func (OperatingSystemType) Type() protoreflect.EnumType {
	return &file_AgentRegistration_proto_enumTypes[2]
}

func (x OperatingSystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatingSystemType.Descriptor instead.
func (OperatingSystemType) EnumDescriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{2}
}

type SystemRegistrationStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber      string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SystemId          string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	RegistrationToken string                 `protobuf:"bytes,3,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	NeedsApiKey       bool                   `protobuf:"varint,4,opt,name=needs_api_key,json=needsApiKey,proto3" json:"needs_api_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemRegistrationStatusRequest) Reset() {
	*x = SystemRegistrationStatusRequest{}
	mi := &file_AgentRegistration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemRegistrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemRegistrationStatusRequest) ProtoMessage() {}

func (x *SystemRegistrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentRegistration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemRegistrationStatusRequest.ProtoReflect.Descriptor instead.
func (*SystemRegistrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{0}
}

func (x *SystemRegistrationStatusRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *SystemRegistrationStatusRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SystemRegistrationStatusRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *SystemRegistrationStatusRequest) GetNeedsApiKey() bool {
	if x != nil {
		return x.NeedsApiKey
	}
	return false
}

type SystemRegistrationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RegistrationStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=agent.RegistrationStatus" json:"status,omitempty"`
	MachineId     int64                  `protobuf:"varint,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemRegistrationStatusResponse) Reset() {
	*x = SystemRegistrationStatusResponse{}
	mi := &file_AgentRegistration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemRegistrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemRegistrationStatusResponse) ProtoMessage() {}

func (x *SystemRegistrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentRegistration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemRegistrationStatusResponse.ProtoReflect.Descriptor instead.
func (*SystemRegistrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{1}
}

func (x *SystemRegistrationStatusResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_UNKNOWN_REGISTRATION
}

func (x *SystemRegistrationStatusResponse) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *SystemRegistrationStatusResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SystemRegistrationStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RegisterSystemRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hostname          string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SerialNumber      string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SystemId          string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	AssetTag          string                 `protobuf:"bytes,4,opt,name=asset_tag,json=assetTag,proto3" json:"asset_tag,omitempty"`
	MachineType       MachineType            `protobuf:"varint,5,opt,name=machine_type,json=machineType,proto3,enum=agent.MachineType" json:"machine_type,omitempty"`
	Os                OperatingSystemType    `protobuf:"varint,6,opt,name=os,proto3,enum=agent.OperatingSystemType" json:"os,omitempty"`
	OsVersion         string                 `protobuf:"bytes,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	RegistrationToken string                 `protobuf:"bytes,8,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterSystemRequest) Reset() {
	*x = RegisterSystemRequest{}
	mi := &file_AgentRegistration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSystemRequest) ProtoMessage() {}

func (x *RegisterSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentRegistration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSystemRequest.ProtoReflect.Descriptor instead.
func (*RegisterSystemRequest) Descriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSystemRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterSystemRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RegisterSystemRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *RegisterSystemRequest) GetAssetTag() string {
	if x != nil {
		return x.AssetTag
	}
	return ""
}

func (x *RegisterSystemRequest) GetMachineType() MachineType {
	if x != nil {
		return x.MachineType
	}
	return MachineType_UNKNOWN_TYPE
}

func (x *RegisterSystemRequest) GetOs() OperatingSystemType {
	if x != nil {
		return x.Os
	}
	return OperatingSystemType_UNKNOWN_OS
}

func (x *RegisterSystemRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterSystemRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

type RegisterSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     int64                  `protobuf:"varint,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSystemResponse) Reset() {
	*x = RegisterSystemResponse{}
	mi := &file_AgentRegistration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSystemResponse) ProtoMessage() {}

func (x *RegisterSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentRegistration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSystemResponse.ProtoReflect.Descriptor instead.
func (*RegisterSystemResponse) Descriptor() ([]byte, []int) {
	return file_AgentRegistration_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSystemResponse) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *RegisterSystemResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterSystemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_AgentRegistration_proto protoreflect.FileDescriptor

const file_AgentRegistration_proto_rawDesc = "" +
	"\n" +
	"\x17AgentRegistration.proto\x12\x05agent\"\xb6\x01\n" +
	"\x1fSystemRegistrationStatusRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12-\n" +
	"\x12registration_token\x18\x03 \x01(\tR\x11registrationToken\x12\"\n" +
	"\rneeds_api_key\x18\x04 \x01(\bR\vneedsApiKey\"\xb2\x01\n" +
	" SystemRegistrationStatusResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.agent.RegistrationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\x03R\tmachineId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xc3\x02\n" +
	"\x15RegisterSystemRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1b\n" +
	"\tsystem_id\x18\x03 \x01(\tR\bsystemId\x12\x1b\n" +
	"\tasset_tag\x18\x04 \x01(\tR\bassetTag\x125\n" +
	"\fmachine_type\x18\x05 \x01(\x0e2\x12.agent.MachineTypeR\vmachineType\x12*\n" +
	"\x02os\x18\x06 \x01(\x0e2\x1a.agent.OperatingSystemTypeR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\a \x01(\tR\tosVersion\x12-\n" +
	"\x12registration_token\x18\b \x01(\tR\x11registrationToken\"u\n" +
	"\x16RegisterSystemResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\x03R\tmachineId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*G\n" +
	"\x12RegistrationStatus\x12\x18\n" +
	"\x14UNKNOWN_REGISTRATION\x10\x00\x12\x17\n" +
	"\x13REGISTRATION_ACTIVE\x10\x01*x\n" +
	"\vMachineType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x10\n" +
	"\fDESKTOP_TYPE\x10\x01\x12\x0f\n" +
	"\vLAPTOP_TYPE\x10\x02\x12\x1a\n" +
	"\x16BARE_METAL_SERVER_TYPE\x10\x03\x12\x18\n" +
	"\x14VIRTUAL_MACHINE_TYPE\x10\x04*n\n" +
	"\x13OperatingSystemType\x12\x0e\n" +
	"\n" +
	"UNKNOWN_OS\x10\x00\x12\x0e\n" +
	"\n" +
	"WINDOWS_OS\x10\x01\x12\n" +
	"\n" +
	"\x06MAC_OS\x10\x02\x12\r\n" +
	"\tUBUNTU_OS\x10\x03\x12\r\n" +
	"\tFEDORA_OS\x10\x04\x12\r\n" +
	"\tREDHAT_OS\x10\x052\xc7\x01\n" +
	"\fRegistration\x12h\n" +
	"\x15GetRegistrationStatus\x12&.agent.SystemRegistrationStatusRequest\x1a'.agent.SystemRegistrationStatusResponse\x12M\n" +
	"\x0eRegisterSystem\x12\x1c.agent.RegisterSystemRequest\x1a\x1d.agent.RegisterSystemResponseB_Z,github.com/framlux/vord/internal/proto/agent\xaa\x02.Framlux.FleetManagement.Grpc.AgentRegistrationb\x06proto3"

var (
	file_AgentRegistration_proto_rawDescOnce sync.Once
	file_AgentRegistration_proto_rawDescData []byte
)

func file_AgentRegistration_proto_rawDescGZIP() []byte {
	file_AgentRegistration_proto_rawDescOnce.Do(func() {
		file_AgentRegistration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AgentRegistration_proto_rawDesc), len(file_AgentRegistration_proto_rawDesc)))
	})
	return file_AgentRegistration_proto_rawDescData
}

var file_AgentRegistration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_AgentRegistration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AgentRegistration_proto_goTypes = []any{
	(RegistrationStatus)(0),                  // 0: agent.RegistrationStatus
	(MachineType)(0),                         // 1: agent.MachineType
	(OperatingSystemType)(0),                 // 2: agent.OperatingSystemType
	(*SystemRegistrationStatusRequest)(nil),  // 3: agent.SystemRegistrationStatusRequest
	(*SystemRegistrationStatusResponse)(nil), // 4: agent.SystemRegistrationStatusResponse
	(*RegisterSystemRequest)(nil),            // 5: agent.RegisterSystemRequest
	(*RegisterSystemResponse)(nil),           // 6: agent.RegisterSystemResponse
}
var file_AgentRegistration_proto_depIdxs = []int32{
	0, // 0: agent.SystemRegistrationStatusResponse.status:type_name -> agent.RegistrationStatus
	1, // 1: agent.RegisterSystemRequest.machine_type:type_name -> agent.MachineType
	2, // 2: agent.RegisterSystemRequest.os:type_name -> agent.OperatingSystemType
	3, // 3: agent.Registration.GetRegistrationStatus:input_type -> agent.SystemRegistrationStatusRequest
	5, // 4: agent.Registration.RegisterSystem:input_type -> agent.RegisterSystemRequest
	4, // 5: agent.Registration.GetRegistrationStatus:output_type -> agent.SystemRegistrationStatusResponse
	6, // 6: agent.Registration.RegisterSystem:output_type -> agent.RegisterSystemResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AgentRegistration_proto_init() }
func file_AgentRegistration_proto_init() {
	if File_AgentRegistration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AgentRegistration_proto_rawDesc), len(file_AgentRegistration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AgentRegistration_proto_goTypes,
		DependencyIndexes: file_AgentRegistration_proto_depIdxs,
		EnumInfos:         file_AgentRegistration_proto_enumTypes,
		MessageInfos:      file_AgentRegistration_proto_msgTypes,
	}.Build()
	File_AgentRegistration_proto = out.File
	file_AgentRegistration_proto_goTypes = nil
	file_AgentRegistration_proto_depIdxs = nil
}
