// Copyright (c) 2026 Framlux LLC
// Licensed under the MIT License
// See LICENSE for details.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: AgentConfiguration.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Configuration_GetConfiguration_FullMethodName   = "/agent.Configuration/GetConfiguration"
	Configuration_AgentPing_FullMethodName          = "/agent.Configuration/AgentPing"
	Configuration_GetPendingCommands_FullMethodName = "/agent.Configuration/GetPendingCommands"
	Configuration_AcknowledgeCommand_FullMethodName = "/agent.Configuration/AcknowledgeCommand"
)

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationClient interface {
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	AgentPing(ctx context.Context, in *AgentPingRequest, opts ...grpc.CallOption) (*AgentPingResponse, error)
	GetPendingCommands(ctx context.Context, in *GetPendingCommandsRequest, opts ...grpc.CallOption) (*GetPendingCommandsResponse, error)
	AcknowledgeCommand(ctx context.Context, in *AcknowledgeCommandRequest, opts ...grpc.CallOption) (*AcknowledgeCommandResponse, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, Configuration_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) AgentPing(ctx context.Context, in *AgentPingRequest, opts ...grpc.CallOption) (*AgentPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentPingResponse)
	err := c.cc.Invoke(ctx, Configuration_AgentPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) GetPendingCommands(ctx context.Context, in *GetPendingCommandsRequest, opts ...grpc.CallOption) (*GetPendingCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingCommandsResponse)
	err := c.cc.Invoke(ctx, Configuration_GetPendingCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) AcknowledgeCommand(ctx context.Context, in *AcknowledgeCommandRequest, opts ...grpc.CallOption) (*AcknowledgeCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeCommandResponse)
	err := c.cc.Invoke(ctx, Configuration_AcknowledgeCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
// All implementations must embed UnimplementedConfigurationServer
// for forward compatibility.
type ConfigurationServer interface {
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	AgentPing(context.Context, *AgentPingRequest) (*AgentPingResponse, error)
	GetPendingCommands(context.Context, *GetPendingCommandsRequest) (*GetPendingCommandsResponse, error)
	AcknowledgeCommand(context.Context, *AcknowledgeCommandRequest) (*AcknowledgeCommandResponse, error)
	mustEmbedUnimplementedConfigurationServer()
}

// UnimplementedConfigurationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationServer struct{}

func (UnimplementedConfigurationServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedConfigurationServer) AgentPing(context.Context, *AgentPingRequest) (*AgentPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentPing not implemented")
}
func (UnimplementedConfigurationServer) GetPendingCommands(context.Context, *GetPendingCommandsRequest) (*GetPendingCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingCommands not implemented")
}
func (UnimplementedConfigurationServer) AcknowledgeCommand(context.Context, *AcknowledgeCommandRequest) (*AcknowledgeCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeCommand not implemented")
}
func (UnimplementedConfigurationServer) mustEmbedUnimplementedConfigurationServer() {}
func (UnimplementedConfigurationServer) testEmbeddedByValue()                       {}

// UnsafeConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServer will
// result in compilation errors.
type UnsafeConfigurationServer interface {
	mustEmbedUnimplementedConfigurationServer()
}

func RegisterConfigurationServer(s grpc.ServiceRegistrar, srv ConfigurationServer) {
	// If the following call panics, it indicates UnimplementedConfigurationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Configuration_ServiceDesc, srv)
}

func _Configuration_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_AgentPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).AgentPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_AgentPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).AgentPing(ctx, req.(*AgentPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_GetPendingCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetPendingCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetPendingCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetPendingCommands(ctx, req.(*GetPendingCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_AcknowledgeCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).AcknowledgeCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_AcknowledgeCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).AcknowledgeCommand(ctx, req.(*AcknowledgeCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Configuration_ServiceDesc is the grpc.ServiceDesc for Configuration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configuration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _Configuration_GetConfiguration_Handler,
		},
		{
			MethodName: "AgentPing",
			Handler:    _Configuration_AgentPing_Handler,
		},
		{
			MethodName: "GetPendingCommands",
			Handler:    _Configuration_GetPendingCommands_Handler,
		},
		{
			MethodName: "AcknowledgeCommand",
			Handler:    _Configuration_AcknowledgeCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AgentConfiguration.proto",
}
