// Copyright (c) 2026 Framlux LLC
// Licensed under the MIT License
// See LICENSE for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: AgentConfiguration.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultType int32

const (
	ResultType_COMPLETED ResultType = 0
	ResultType_INITIATED ResultType = 1
	ResultType_REJECTED  ResultType = 2
)

// Enum value maps for ResultType.
var (
	ResultType_name = map[int32]string{
		0: "COMPLETED",
		1: "INITIATED",
		2: "REJECTED",
	}
	ResultType_value = map[string]int32{
		"COMPLETED": 0,
		"INITIATED": 1,
		"REJECTED":  2,
	}
)

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}

func (x ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_AgentConfiguration_proto_enumTypes[0].Descriptor()
}

func (ResultType) Type() protoreflect.EnumType {
	return &file_AgentConfiguration_proto_enumTypes[0]
}

func (x ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultType.Descriptor instead.
func (ResultType) EnumDescriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{0}
}

type GetConfigurationRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId int64                  `protobuf:"varint,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Bitwise agent capabilities: bit 0 = remote commands enabled.
	AgentCapabilities uint64 `protobuf:"varint,2,opt,name=agent_capabilities,json=agentCapabilities,proto3" json:"agent_capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_AgentConfiguration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigurationRequest) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *GetConfigurationRequest) GetAgentCapabilities() uint64 {
	if x != nil {
		return x.AgentCapabilities
	}
	return 0
}

type GetConfigurationResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TimeConfig *TimingConfiguration   `protobuf:"bytes,1,opt,name=time_config,json=timeConfig,proto3" json:"time_config,omitempty"`
	// Version identifier so agents can detect stale configs without full comparison.
	ConfigVersion int64 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Active signing keys for the machine's tenant, used to verify remote command signatures.
	SigningKeys []*TrustedSigningKey `protobuf:"bytes,3,rep,name=signing_keys,json=signingKeys,proto3" json:"signing_keys,omitempty"`
	// Monotonic counter incremented on key registration/revocation; agents skip sync if unchanged.
	SigningKeyVersion int64 `protobuf:"varint,4,opt,name=signing_key_version,json=signingKeyVersion,proto3" json:"signing_key_version,omitempty"`
	// The tenant ID this machine belongs to, so the agent can verify command ownership.
	TenantId int32 `protobuf:"varint,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Rotated API key. Non-empty when the server has re-issued this machine's credential.
	ApiKey        string `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_AgentConfiguration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigurationResponse) GetTimeConfig() *TimingConfiguration {
	if x != nil {
		return x.TimeConfig
	}
	return nil
}

func (x *GetConfigurationResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *GetConfigurationResponse) GetSigningKeys() []*TrustedSigningKey {
	if x != nil {
		return x.SigningKeys
	}
	return nil
}

func (x *GetConfigurationResponse) GetSigningKeyVersion() int64 {
	if x != nil {
		return x.SigningKeyVersion
	}
	return 0
}

func (x *GetConfigurationResponse) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetConfigurationResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type TrustedSigningKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         int32                  `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustedSigningKey) Reset() {
	*x = TrustedSigningKey{}
	mi := &file_AgentConfiguration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedSigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedSigningKey) ProtoMessage() {}

func (x *TrustedSigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedSigningKey.ProtoReflect.Descriptor instead.
func (*TrustedSigningKey) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{2}
}

func (x *TrustedSigningKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *TrustedSigningKey) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrustedSigningKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type TimingConfiguration struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatTimeInSeconds            int32                  `protobuf:"varint,1,opt,name=heartbeat_time_in_seconds,json=heartbeatTimeInSeconds,proto3" json:"heartbeat_time_in_seconds,omitempty"`
	ConfigurationRefreshTimeInSeconds int32                  `protobuf:"varint,2,opt,name=configuration_refresh_time_in_seconds,json=configurationRefreshTimeInSeconds,proto3" json:"configuration_refresh_time_in_seconds,omitempty"`
	// Dedicated polling interval for remote command checks (default: 30s).
	CommandPollTimeInSeconds int32 `protobuf:"varint,3,opt,name=command_poll_time_in_seconds,json=commandPollTimeInSeconds,proto3" json:"command_poll_time_in_seconds,omitempty"`
	// Fast telemetry collection interval in seconds (default: 30, range: 10-300).
	TelemetryCollectFastSeconds int32 `protobuf:"varint,4,opt,name=telemetry_collect_fast_seconds,json=telemetryCollectFastSeconds,proto3" json:"telemetry_collect_fast_seconds,omitempty"`
	// Slow telemetry collection interval in seconds (default: 900, range: 60-3600).
	TelemetryCollectSlowSeconds int32 `protobuf:"varint,5,opt,name=telemetry_collect_slow_seconds,json=telemetryCollectSlowSeconds,proto3" json:"telemetry_collect_slow_seconds,omitempty"`
	// Fast telemetry send interval in seconds (default: 15, range: 5-120).
	TelemetrySendFastSeconds int32 `protobuf:"varint,6,opt,name=telemetry_send_fast_seconds,json=telemetrySendFastSeconds,proto3" json:"telemetry_send_fast_seconds,omitempty"`
	// Slow telemetry send interval in seconds (default: 300, range: 30-1800).
	TelemetrySendSlowSeconds int32 `protobuf:"varint,7,opt,name=telemetry_send_slow_seconds,json=telemetrySendSlowSeconds,proto3" json:"telemetry_send_slow_seconds,omitempty"`
	// Service status collection interval in seconds (default: 3600, range: 60-86400).
	ServiceStatusSeconds int32 `protobuf:"varint,8,opt,name=service_status_seconds,json=serviceStatusSeconds,proto3" json:"service_status_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TimingConfiguration) Reset() {
	*x = TimingConfiguration{}
	mi := &file_AgentConfiguration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingConfiguration) ProtoMessage() {}

func (x *TimingConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingConfiguration.ProtoReflect.Descriptor instead.
func (*TimingConfiguration) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{3}
}

func (x *TimingConfiguration) GetHeartbeatTimeInSeconds() int32 {
	if x != nil {
		return x.HeartbeatTimeInSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetConfigurationRefreshTimeInSeconds() int32 {
	if x != nil {
		return x.ConfigurationRefreshTimeInSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetCommandPollTimeInSeconds() int32 {
	if x != nil {
		return x.CommandPollTimeInSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetTelemetryCollectFastSeconds() int32 {
	if x != nil {
		return x.TelemetryCollectFastSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetTelemetryCollectSlowSeconds() int32 {
	if x != nil {
		return x.TelemetryCollectSlowSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetTelemetrySendFastSeconds() int32 {
	if x != nil {
		return x.TelemetrySendFastSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetTelemetrySendSlowSeconds() int32 {
	if x != nil {
		return x.TelemetrySendSlowSeconds
	}
	return 0
}

func (x *TimingConfiguration) GetServiceStatusSeconds() int32 {
	if x != nil {
		return x.ServiceStatusSeconds
	}
	return 0
}

type AgentPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     int64                  `protobuf:"varint,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPingRequest) Reset() {
	*x = AgentPingRequest{}
	mi := &file_AgentConfiguration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPingRequest) ProtoMessage() {}

func (x *AgentPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPingRequest.ProtoReflect.Descriptor instead.
func (*AgentPingRequest) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{4}
}

func (x *AgentPingRequest) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

type AgentPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPingResponse) Reset() {
	*x = AgentPingResponse{}
	mi := &file_AgentConfiguration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPingResponse) ProtoMessage() {}

func (x *AgentPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPingResponse.ProtoReflect.Descriptor instead.
func (*AgentPingResponse) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{5}
}

func (x *AgentPingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPendingCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     int64                  `protobuf:"varint,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsRequest) Reset() {
	*x = GetPendingCommandsRequest{}
	mi := &file_AgentConfiguration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsRequest) ProtoMessage() {}

func (x *GetPendingCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsRequest) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingCommandsRequest) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

type GetPendingCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*AgentCommand        `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsResponse) Reset() {
	*x = GetPendingCommandsResponse{}
	mi := &file_AgentConfiguration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsResponse) ProtoMessage() {}

func (x *GetPendingCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsResponse) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingCommandsResponse) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AgentCommand struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type   string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Params map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The exact canonical JSON payload that was signed by the user.
	CanonicalPayload string `protobuf:"bytes,4,opt,name=canonical_payload,json=canonicalPayload,proto3" json:"canonical_payload,omitempty"`
	// Ed25519 signature over canonical_payload.
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// The signing key ID used for signature verification lookup.
	SigningKeyId int32 `protobuf:"varint,6,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	// Timestamp from the signed payload (ISO 8601).
	Timestamp string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Expiry time from the signed payload (ISO 8601).
	ExpiresAt string `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Unique nonce for replay prevention.
	Nonce string `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// User who issued the command.
	UserId int32 `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Tenant the command belongs to.
	TenantId int32 `protobuf:"varint,11,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Target machine ID for ownership verification.
	MachineId     int64 `protobuf:"varint,12,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_AgentConfiguration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{8}
}

func (x *AgentCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AgentCommand) GetCanonicalPayload() string {
	if x != nil {
		return x.CanonicalPayload
	}
	return ""
}

func (x *AgentCommand) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AgentCommand) GetSigningKeyId() int32 {
	if x != nil {
		return x.SigningKeyId
	}
	return 0
}

func (x *AgentCommand) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AgentCommand) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AgentCommand) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AgentCommand) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AgentCommand) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *AgentCommand) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

type AcknowledgeCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	MachineId     int64                  `protobuf:"varint,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Result        *CommandResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeCommandRequest) Reset() {
	*x = AcknowledgeCommandRequest{}
	mi := &file_AgentConfiguration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeCommandRequest) ProtoMessage() {}

func (x *AcknowledgeCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeCommandRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeCommandRequest) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{9}
}

func (x *AcknowledgeCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AcknowledgeCommandRequest) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *AcknowledgeCommandRequest) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CommandResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout   string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Message  string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Distinguishes immediate results from delayed/destructive commands.
	ResultType    ResultType `protobuf:"varint,6,opt,name=result_type,json=resultType,proto3,enum=agent.ResultType" json:"result_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_AgentConfiguration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetResultType() ResultType {
	if x != nil {
		return x.ResultType
	}
	return ResultType_COMPLETED
}

type AcknowledgeCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeCommandResponse) Reset() {
	*x = AcknowledgeCommandResponse{}
	mi := &file_AgentConfiguration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeCommandResponse) ProtoMessage() {}

func (x *AcknowledgeCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AgentConfiguration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeCommandResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeCommandResponse) Descriptor() ([]byte, []int) {
	return file_AgentConfiguration_proto_rawDescGZIP(), []int{11}
}

func (x *AcknowledgeCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_AgentConfiguration_proto protoreflect.FileDescriptor

const file_AgentConfiguration_proto_rawDesc = "" +
	"\n" +
	"\x18AgentConfiguration.proto\x12\x05agent\"g\n" +
	"\x17GetConfigurationRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\x03R\tmachineId\x12-\n" +
	"\x12agent_capabilities\x18\x02 \x01(\x04R\x11agentCapabilities\"\xa1\x02\n" +
	"\x18GetConfigurationResponse\x12;\n" +
	"\vtime_config\x18\x01 \x01(\v2\x1a.agent.TimingConfigurationR\n" +
	"timeConfig\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x03R\rconfigVersion\x12;\n" +
	"\fsigning_keys\x18\x03 \x03(\v2\x18.agent.TrustedSigningKeyR\vsigningKeys\x12.\n" +
	"\x13signing_key_version\x18\x04 \x01(\x03R\x11signingKeyVersion\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\x05R\btenantId\x12\x17\n" +
	"\aapi_key\x18\x06 \x01(\tR\x06apiKey\"b\n" +
	"\x11TrustedSigningKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\x05R\x05keyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\xa0\x04\n" +
	"\x13TimingConfiguration\x129\n" +
	"\x19heartbeat_time_in_seconds\x18\x01 \x01(\x05R\x16heartbeatTimeInSeconds\x12P\n" +
	"%configuration_refresh_time_in_seconds\x18\x02 \x01(\x05R!configurationRefreshTimeInSeconds\x12>\n" +
	"\x1ccommand_poll_time_in_seconds\x18\x03 \x01(\x05R\x18commandPollTimeInSeconds\x12C\n" +
	"\x1etelemetry_collect_fast_seconds\x18\x04 \x01(\x05R\x1btelemetryCollectFastSeconds\x12C\n" +
	"\x1etelemetry_collect_slow_seconds\x18\x05 \x01(\x05R\x1btelemetryCollectSlowSeconds\x12=\n" +
	"\x1btelemetry_send_fast_seconds\x18\x06 \x01(\x05R\x18telemetrySendFastSeconds\x12=\n" +
	"\x1btelemetry_send_slow_seconds\x18\a \x01(\x05R\x18telemetrySendSlowSeconds\x124\n" +
	"\x16service_status_seconds\x18\b \x01(\x05R\x14serviceStatusSeconds\"1\n" +
	"\x10AgentPingRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\x03R\tmachineId\"-\n" +
	"\x11AgentPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x19GetPendingCommandsRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\x03R\tmachineId\"M\n" +
	"\x1aGetPendingCommandsResponse\x12/\n" +
	"\bcommands\x18\x01 \x03(\v2\x13.agent.AgentCommandR\bcommands\"\xbf\x03\n" +
	"\fAgentCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\x06params\x18\x03 \x03(\v2\x1f.agent.AgentCommand.ParamsEntryR\x06params\x12+\n" +
	"\x11canonical_payload\x18\x04 \x01(\tR\x10canonicalPayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12$\n" +
	"\x0esigning_key_id\x18\x06 \x01(\x05R\fsigningKeyId\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05nonce\x18\t \x01(\tR\x05nonce\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x05R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\v \x01(\x05R\btenantId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\f \x01(\x03R\tmachineId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x19AcknowledgeCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\x03R\tmachineId\x12,\n" +
	"\x06result\x18\x03 \x01(\v2\x14.agent.CommandResultR\x06result\"\xc4\x01\n" +
	"\rCommandResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x122\n" +
	"\vresult_type\x18\x06 \x01(\x0e2\x11.agent.ResultTypeR\n" +
	"resultType\"6\n" +
	"\x1aAcknowledgeCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*8\n" +
	"\n" +
	"ResultType\x12\r\n" +
	"\tCOMPLETED\x10\x00\x12\r\n" +
	"\tINITIATED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x022\xda\x02\n" +
	"\rConfiguration\x12S\n" +
	"\x10GetConfiguration\x12\x1e.agent.GetConfigurationRequest\x1a\x1f.agent.GetConfigurationResponse\x12>\n" +
	"\tAgentPing\x12\x17.agent.AgentPingRequest\x1a\x18.agent.AgentPingResponse\x12Y\n" +
	"\x12GetPendingCommands\x12 .agent.GetPendingCommandsRequest\x1a!.agent.GetPendingCommandsResponse\x12Y\n" +
	"\x12AcknowledgeCommand\x12 .agent.AcknowledgeCommandRequest\x1a!.agent.AcknowledgeCommandResponseB`Z,github.com/framlux/vord/internal/proto/agent\xaa\x02/Framlux.FleetManagement.Grpc.AgentConfigurationb\x06proto3"

var (
	file_AgentConfiguration_proto_rawDescOnce sync.Once
	file_AgentConfiguration_proto_rawDescData []byte
)

func file_AgentConfiguration_proto_rawDescGZIP() []byte {
	file_AgentConfiguration_proto_rawDescOnce.Do(func() {
		file_AgentConfiguration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AgentConfiguration_proto_rawDesc), len(file_AgentConfiguration_proto_rawDesc)))
	})
	return file_AgentConfiguration_proto_rawDescData
}

var file_AgentConfiguration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AgentConfiguration_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_AgentConfiguration_proto_goTypes = []any{
	(ResultType)(0),                    // 0: agent.ResultType
	(*GetConfigurationRequest)(nil),    // 1: agent.GetConfigurationRequest
	(*GetConfigurationResponse)(nil),   // 2: agent.GetConfigurationResponse
	(*TrustedSigningKey)(nil),          // 3: agent.TrustedSigningKey
	(*TimingConfiguration)(nil),        // 4: agent.TimingConfiguration
	(*AgentPingRequest)(nil),           // 5: agent.AgentPingRequest
	(*AgentPingResponse)(nil),          // 6: agent.AgentPingResponse
	(*GetPendingCommandsRequest)(nil),  // 7: agent.GetPendingCommandsRequest
	(*GetPendingCommandsResponse)(nil), // 8: agent.GetPendingCommandsResponse
	(*AgentCommand)(nil),               // 9: agent.AgentCommand
	(*AcknowledgeCommandRequest)(nil),  // 10: agent.AcknowledgeCommandRequest
	(*CommandResult)(nil),              // 11: agent.CommandResult
	(*AcknowledgeCommandResponse)(nil), // 12: agent.AcknowledgeCommandResponse
	nil,                                // 13: agent.AgentCommand.ParamsEntry
}
var file_AgentConfiguration_proto_depIdxs = []int32{
	4,  // 0: agent.GetConfigurationResponse.time_config:type_name -> agent.TimingConfiguration
	3,  // 1: agent.GetConfigurationResponse.signing_keys:type_name -> agent.TrustedSigningKey
	9,  // 2: agent.GetPendingCommandsResponse.commands:type_name -> agent.AgentCommand
	13, // 3: agent.AgentCommand.params:type_name -> agent.AgentCommand.ParamsEntry
	11, // 4: agent.AcknowledgeCommandRequest.result:type_name -> agent.CommandResult
	0,  // 5: agent.CommandResult.result_type:type_name -> agent.ResultType
	1,  // 6: agent.Configuration.GetConfiguration:input_type -> agent.GetConfigurationRequest
	5,  // 7: agent.Configuration.AgentPing:input_type -> agent.AgentPingRequest
	7,  // 8: agent.Configuration.GetPendingCommands:input_type -> agent.GetPendingCommandsRequest
	10, // 9: agent.Configuration.AcknowledgeCommand:input_type -> agent.AcknowledgeCommandRequest
	2,  // 10: agent.Configuration.GetConfiguration:output_type -> agent.GetConfigurationResponse
	6,  // 11: agent.Configuration.AgentPing:output_type -> agent.AgentPingResponse
	8,  // 12: agent.Configuration.GetPendingCommands:output_type -> agent.GetPendingCommandsResponse
	12, // 13: agent.Configuration.AcknowledgeCommand:output_type -> agent.AcknowledgeCommandResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_AgentConfiguration_proto_init() }
func file_AgentConfiguration_proto_init() {
	if File_AgentConfiguration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AgentConfiguration_proto_rawDesc), len(file_AgentConfiguration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AgentConfiguration_proto_goTypes,
		DependencyIndexes: file_AgentConfiguration_proto_depIdxs,
		EnumInfos:         file_AgentConfiguration_proto_enumTypes,
		MessageInfos:      file_AgentConfiguration_proto_msgTypes,
	}.Build()
	File_AgentConfiguration_proto = out.File
	file_AgentConfiguration_proto_goTypes = nil
	file_AgentConfiguration_proto_depIdxs = nil
}
