// Copyright (c) 2026 Framlux LLC
// Licensed under the MIT License
// See LICENSE for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: AgentTelemetry.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryTypes int32

const (
	TelemetryTypes_TELEMETRY_UNKNOWN       TelemetryTypes = 0
	TelemetryTypes_SYSTEM_INFO_TYPE        TelemetryTypes = 1
	TelemetryTypes_OS_VERSION_TYPE         TelemetryTypes = 2
	TelemetryTypes_CPU_INFO_TYPE           TelemetryTypes = 3
	TelemetryTypes_MEMORY_INFO_TYPE        TelemetryTypes = 4
	TelemetryTypes_DISK_INFO_TYPE          TelemetryTypes = 5
	TelemetryTypes_CPU_UTILIZATION_TYPE    TelemetryTypes = 6
	TelemetryTypes_MEMORY_UTILIZATION_TYPE TelemetryTypes = 7
	TelemetryTypes_DISK_UTILIZATION_TYPE   TelemetryTypes = 8
	TelemetryTypes_SSH_SESSION_TYPE        TelemetryTypes = 9
	TelemetryTypes_HARDWARE_HEALTH_TYPE    TelemetryTypes = 10
	TelemetryTypes_PACKAGE_UPDATES_TYPE    TelemetryTypes = 11
	TelemetryTypes_SERVICE_STATUS_TYPE     TelemetryTypes = 12
)

// Enum value maps for TelemetryTypes.
var (
	TelemetryTypes_name = map[int32]string{
		0:  "TELEMETRY_UNKNOWN",
		1:  "SYSTEM_INFO_TYPE",
		2:  "OS_VERSION_TYPE",
		3:  "CPU_INFO_TYPE",
		4:  "MEMORY_INFO_TYPE",
		5:  "DISK_INFO_TYPE",
		6:  "CPU_UTILIZATION_TYPE",
		7:  "MEMORY_UTILIZATION_TYPE",
		8:  "DISK_UTILIZATION_TYPE",
		9:  "SSH_SESSION_TYPE",
		10: "HARDWARE_HEALTH_TYPE",
		11: "PACKAGE_UPDATES_TYPE",
		12: "SERVICE_STATUS_TYPE",
	}
	TelemetryTypes_value = map[string]int32{
		"TELEMETRY_UNKNOWN":       0,
		"SYSTEM_INFO_TYPE":        1,
		"OS_VERSION_TYPE":         2,
		"CPU_INFO_TYPE":           3,
		"MEMORY_INFO_TYPE":        4,
		"DISK_INFO_TYPE":          5,
		"CPU_UTILIZATION_TYPE":    6,
		"MEMORY_UTILIZATION_TYPE": 7,
		"DISK_UTILIZATION_TYPE":   8,
		"SSH_SESSION_TYPE":        9,
		"HARDWARE_HEALTH_TYPE":    10,
		"PACKAGE_UPDATES_TYPE":    11,
		"SERVICE_STATUS_TYPE":     12,
	}
)

func (x TelemetryTypes) Enum() *TelemetryTypes {
	p := new(TelemetryTypes)
	*p = x
	return p
}

func (x TelemetryTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_AgentTelemetry_proto_enumTypes[0].Descriptor()
}

func (TelemetryTypes) Type() protoreflect.EnumType {
	return &file_AgentTelemetry_proto_enumTypes[0]
}

func (x TelemetryTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryTypes.Descriptor instead.
func (TelemetryTypes) EnumDescriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{0}
}

type TelemetryEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	AgentTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=agent_timestamp,json=agentTimestamp,proto3" json:"agent_timestamp,omitempty"`
	Items          []*TelemetryItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryEnvelope) Reset() {
	*x = TelemetryEnvelope{}
	mi := &file_AgentTelemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEnvelope) ProtoMessage() {}

func (x *TelemetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEnvelope.ProtoReflect.Descriptor instead.
func (*TelemetryEnvelope) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEnvelope) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TelemetryEnvelope) GetAgentTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AgentTimestamp
	}
	return nil
}

func (x *TelemetryEnvelope) GetItems() []*TelemetryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TelemetryItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type        TelemetryTypes         `protobuf:"varint,2,opt,name=type,proto3,enum=agent.TelemetryTypes" json:"type,omitempty"`
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryItem_SystemInfo
	//	*TelemetryItem_OsVersion
	//	*TelemetryItem_CpuInfo
	//	*TelemetryItem_MemoryInfo
	//	*TelemetryItem_DiskInfo
	//	*TelemetryItem_CpuUtilization
	//	*TelemetryItem_MemoryUtilization
	//	*TelemetryItem_DiskUtilization
	//	*TelemetryItem_SshSession
	//	*TelemetryItem_HardwareHealth
	//	*TelemetryItem_PackageUpdates
	//	*TelemetryItem_ServiceStatus
	Payload       isTelemetryItem_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryItem) Reset() {
	*x = TelemetryItem{}
	mi := &file_AgentTelemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryItem) ProtoMessage() {}

func (x *TelemetryItem) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryItem.ProtoReflect.Descriptor instead.
func (*TelemetryItem) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryItem) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TelemetryItem) GetType() TelemetryTypes {
	if x != nil {
		return x.Type
	}
	return TelemetryTypes_TELEMETRY_UNKNOWN
}

func (x *TelemetryItem) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *TelemetryItem) GetPayload() isTelemetryItem_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryItem) GetSystemInfo() *SystemInfoRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_SystemInfo); ok {
			return x.SystemInfo
		}
	}
	return nil
}

func (x *TelemetryItem) GetOsVersion() *OsVersionRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_OsVersion); ok {
			return x.OsVersion
		}
	}
	return nil
}

func (x *TelemetryItem) GetCpuInfo() *CpuInfoRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_CpuInfo); ok {
			return x.CpuInfo
		}
	}
	return nil
}

func (x *TelemetryItem) GetMemoryInfo() *MemoryInfoRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_MemoryInfo); ok {
			return x.MemoryInfo
		}
	}
	return nil
}

func (x *TelemetryItem) GetDiskInfo() *DiskInfoRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_DiskInfo); ok {
			return x.DiskInfo
		}
	}
	return nil
}

func (x *TelemetryItem) GetCpuUtilization() *CpuUtilizationRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_CpuUtilization); ok {
			return x.CpuUtilization
		}
	}
	return nil
}

func (x *TelemetryItem) GetMemoryUtilization() *MemoryUtilizationRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_MemoryUtilization); ok {
			return x.MemoryUtilization
		}
	}
	return nil
}

func (x *TelemetryItem) GetDiskUtilization() *DiskUtilizationRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_DiskUtilization); ok {
			return x.DiskUtilization
		}
	}
	return nil
}

func (x *TelemetryItem) GetSshSession() *SshSessionRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_SshSession); ok {
			return x.SshSession
		}
	}
	return nil
}

func (x *TelemetryItem) GetHardwareHealth() *HardwareHealthRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_HardwareHealth); ok {
			return x.HardwareHealth
		}
	}
	return nil
}

func (x *TelemetryItem) GetPackageUpdates() *PackageUpdatesRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_PackageUpdates); ok {
			return x.PackageUpdates
		}
	}
	return nil
}

func (x *TelemetryItem) GetServiceStatus() *ServiceStatusRecord {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryItem_ServiceStatus); ok {
			return x.ServiceStatus
		}
	}
	return nil
}

type isTelemetryItem_Payload interface {
	isTelemetryItem_Payload()
}

type TelemetryItem_SystemInfo struct {
	SystemInfo *SystemInfoRecord `protobuf:"bytes,10,opt,name=system_info,json=systemInfo,proto3,oneof"`
}

type TelemetryItem_OsVersion struct {
	OsVersion *OsVersionRecord `protobuf:"bytes,11,opt,name=os_version,json=osVersion,proto3,oneof"`
}

type TelemetryItem_CpuInfo struct {
	CpuInfo *CpuInfoRecord `protobuf:"bytes,12,opt,name=cpu_info,json=cpuInfo,proto3,oneof"`
}

type TelemetryItem_MemoryInfo struct {
	MemoryInfo *MemoryInfoRecord `protobuf:"bytes,13,opt,name=memory_info,json=memoryInfo,proto3,oneof"`
}

type TelemetryItem_DiskInfo struct {
	DiskInfo *DiskInfoRecord `protobuf:"bytes,14,opt,name=disk_info,json=diskInfo,proto3,oneof"`
}

type TelemetryItem_CpuUtilization struct {
	CpuUtilization *CpuUtilizationRecord `protobuf:"bytes,15,opt,name=cpu_utilization,json=cpuUtilization,proto3,oneof"`
}

type TelemetryItem_MemoryUtilization struct {
	MemoryUtilization *MemoryUtilizationRecord `protobuf:"bytes,16,opt,name=memory_utilization,json=memoryUtilization,proto3,oneof"`
}

type TelemetryItem_DiskUtilization struct {
	DiskUtilization *DiskUtilizationRecord `protobuf:"bytes,17,opt,name=disk_utilization,json=diskUtilization,proto3,oneof"`
}

type TelemetryItem_SshSession struct {
	SshSession *SshSessionRecord `protobuf:"bytes,18,opt,name=ssh_session,json=sshSession,proto3,oneof"`
}

type TelemetryItem_HardwareHealth struct {
	HardwareHealth *HardwareHealthRecord `protobuf:"bytes,19,opt,name=hardware_health,json=hardwareHealth,proto3,oneof"`
}

type TelemetryItem_PackageUpdates struct {
	PackageUpdates *PackageUpdatesRecord `protobuf:"bytes,20,opt,name=package_updates,json=packageUpdates,proto3,oneof"`
}

type TelemetryItem_ServiceStatus struct {
	ServiceStatus *ServiceStatusRecord `protobuf:"bytes,21,opt,name=service_status,json=serviceStatus,proto3,oneof"`
}

func (*TelemetryItem_SystemInfo) isTelemetryItem_Payload() {}

func (*TelemetryItem_OsVersion) isTelemetryItem_Payload() {}

func (*TelemetryItem_CpuInfo) isTelemetryItem_Payload() {}

func (*TelemetryItem_MemoryInfo) isTelemetryItem_Payload() {}

func (*TelemetryItem_DiskInfo) isTelemetryItem_Payload() {}

func (*TelemetryItem_CpuUtilization) isTelemetryItem_Payload() {}

func (*TelemetryItem_MemoryUtilization) isTelemetryItem_Payload() {}

func (*TelemetryItem_DiskUtilization) isTelemetryItem_Payload() {}

func (*TelemetryItem_SshSession) isTelemetryItem_Payload() {}

func (*TelemetryItem_HardwareHealth) isTelemetryItem_Payload() {}

func (*TelemetryItem_PackageUpdates) isTelemetryItem_Payload() {}

func (*TelemetryItem_ServiceStatus) isTelemetryItem_Payload() {}

type TelemetryAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatchId              string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	AcknowledgedEventIds []string               `protobuf:"bytes,2,rep,name=acknowledged_event_ids,json=acknowledgedEventIds,proto3" json:"acknowledged_event_ids,omitempty"`
	Success              bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_AgentTelemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TelemetryAck) GetAcknowledgedEventIds() []string {
	if x != nil {
		return x.AcknowledgedEventIds
	}
	return nil
}

func (x *TelemetryAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SystemInfoRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uuid             string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CpuType          string                 `protobuf:"bytes,3,opt,name=cpu_type,json=cpuType,proto3" json:"cpu_type,omitempty"`
	CpuSubtype       string                 `protobuf:"bytes,4,opt,name=cpu_subtype,json=cpuSubtype,proto3" json:"cpu_subtype,omitempty"`
	CpuBrand         string                 `protobuf:"bytes,5,opt,name=cpu_brand,json=cpuBrand,proto3" json:"cpu_brand,omitempty"`
	CpuPhysicalCores int32                  `protobuf:"varint,6,opt,name=cpu_physical_cores,json=cpuPhysicalCores,proto3" json:"cpu_physical_cores,omitempty"`
	CpuLogicalCores  int32                  `protobuf:"varint,7,opt,name=cpu_logical_cores,json=cpuLogicalCores,proto3" json:"cpu_logical_cores,omitempty"`
	CpuMicrocode     string                 `protobuf:"bytes,8,opt,name=cpu_microcode,json=cpuMicrocode,proto3" json:"cpu_microcode,omitempty"`
	PhysicalMemory   int64                  `protobuf:"varint,9,opt,name=physical_memory,json=physicalMemory,proto3" json:"physical_memory,omitempty"`
	HardwareVendor   string                 `protobuf:"bytes,10,opt,name=hardware_vendor,json=hardwareVendor,proto3" json:"hardware_vendor,omitempty"`
	HardwareModel    string                 `protobuf:"bytes,11,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	HardwareVersion  string                 `protobuf:"bytes,12,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	HardwareSerial   string                 `protobuf:"bytes,13,opt,name=hardware_serial,json=hardwareSerial,proto3" json:"hardware_serial,omitempty"`
	BoardVendor      string                 `protobuf:"bytes,14,opt,name=board_vendor,json=boardVendor,proto3" json:"board_vendor,omitempty"`
	BoardModel       string                 `protobuf:"bytes,15,opt,name=board_model,json=boardModel,proto3" json:"board_model,omitempty"`
	BoardVersion     string                 `protobuf:"bytes,16,opt,name=board_version,json=boardVersion,proto3" json:"board_version,omitempty"`
	BoardSerial      string                 `protobuf:"bytes,17,opt,name=board_serial,json=boardSerial,proto3" json:"board_serial,omitempty"`
	ComputerName     string                 `protobuf:"bytes,18,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	LocalHostname    string                 `protobuf:"bytes,19,opt,name=local_hostname,json=localHostname,proto3" json:"local_hostname,omitempty"`
	EmulatedCpuType  string                 `protobuf:"bytes,20,opt,name=emulated_cpu_type,json=emulatedCpuType,proto3" json:"emulated_cpu_type,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,21,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	BiosVersion      string                 `protobuf:"bytes,22,opt,name=bios_version,json=biosVersion,proto3" json:"bios_version,omitempty"`
	IpAddresses      []string               `protobuf:"bytes,23,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemInfoRecord) Reset() {
	*x = SystemInfoRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRecord) ProtoMessage() {}

func (x *SystemInfoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRecord.ProtoReflect.Descriptor instead.
func (*SystemInfoRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{3}
}

func (x *SystemInfoRecord) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfoRecord) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SystemInfoRecord) GetCpuType() string {
	if x != nil {
		return x.CpuType
	}
	return ""
}

func (x *SystemInfoRecord) GetCpuSubtype() string {
	if x != nil {
		return x.CpuSubtype
	}
	return ""
}

func (x *SystemInfoRecord) GetCpuBrand() string {
	if x != nil {
		return x.CpuBrand
	}
	return ""
}

func (x *SystemInfoRecord) GetCpuPhysicalCores() int32 {
	if x != nil {
		return x.CpuPhysicalCores
	}
	return 0
}

func (x *SystemInfoRecord) GetCpuLogicalCores() int32 {
	if x != nil {
		return x.CpuLogicalCores
	}
	return 0
}

func (x *SystemInfoRecord) GetCpuMicrocode() string {
	if x != nil {
		return x.CpuMicrocode
	}
	return ""
}

func (x *SystemInfoRecord) GetPhysicalMemory() int64 {
	if x != nil {
		return x.PhysicalMemory
	}
	return 0
}

func (x *SystemInfoRecord) GetHardwareVendor() string {
	if x != nil {
		return x.HardwareVendor
	}
	return ""
}

func (x *SystemInfoRecord) GetHardwareModel() string {
	if x != nil {
		return x.HardwareModel
	}
	return ""
}

func (x *SystemInfoRecord) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *SystemInfoRecord) GetHardwareSerial() string {
	if x != nil {
		return x.HardwareSerial
	}
	return ""
}

func (x *SystemInfoRecord) GetBoardVendor() string {
	if x != nil {
		return x.BoardVendor
	}
	return ""
}

func (x *SystemInfoRecord) GetBoardModel() string {
	if x != nil {
		return x.BoardModel
	}
	return ""
}

func (x *SystemInfoRecord) GetBoardVersion() string {
	if x != nil {
		return x.BoardVersion
	}
	return ""
}

func (x *SystemInfoRecord) GetBoardSerial() string {
	if x != nil {
		return x.BoardSerial
	}
	return ""
}

func (x *SystemInfoRecord) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *SystemInfoRecord) GetLocalHostname() string {
	if x != nil {
		return x.LocalHostname
	}
	return ""
}

func (x *SystemInfoRecord) GetEmulatedCpuType() string {
	if x != nil {
		return x.EmulatedCpuType
	}
	return ""
}

func (x *SystemInfoRecord) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfoRecord) GetBiosVersion() string {
	if x != nil {
		return x.BiosVersion
	}
	return ""
}

func (x *SystemInfoRecord) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type OsVersionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Major         int32                  `protobuf:"varint,3,opt,name=major,proto3" json:"major,omitempty"`
	Minor         int32                  `protobuf:"varint,4,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         int32                  `protobuf:"varint,5,opt,name=patch,proto3" json:"patch,omitempty"`
	Build         string                 `protobuf:"bytes,6,opt,name=build,proto3" json:"build,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	Codename      string                 `protobuf:"bytes,8,opt,name=codename,proto3" json:"codename,omitempty"`
	Arch          string                 `protobuf:"bytes,9,opt,name=arch,proto3" json:"arch,omitempty"`
	Extra         string                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	InstallDate   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=install_date,json=installDate,proto3" json:"install_date,omitempty"`
	Revision      string                 `protobuf:"bytes,12,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsVersionRecord) Reset() {
	*x = OsVersionRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsVersionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsVersionRecord) ProtoMessage() {}

func (x *OsVersionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsVersionRecord.ProtoReflect.Descriptor instead.
func (*OsVersionRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{4}
}

func (x *OsVersionRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OsVersionRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OsVersionRecord) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *OsVersionRecord) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *OsVersionRecord) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *OsVersionRecord) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *OsVersionRecord) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *OsVersionRecord) GetCodename() string {
	if x != nil {
		return x.Codename
	}
	return ""
}

func (x *OsVersionRecord) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *OsVersionRecord) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *OsVersionRecord) GetInstallDate() *timestamppb.Timestamp {
	if x != nil {
		return x.InstallDate
	}
	return nil
}

func (x *OsVersionRecord) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type CpuInfoRecord struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId                 string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Model                    string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer             string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProcessorType            string                 `protobuf:"bytes,4,opt,name=processor_type,json=processorType,proto3" json:"processor_type,omitempty"`
	CpuStatus                int32                  `protobuf:"varint,5,opt,name=cpu_status,json=cpuStatus,proto3" json:"cpu_status,omitempty"`
	NumberOfCores            string                 `protobuf:"bytes,6,opt,name=number_of_cores,json=numberOfCores,proto3" json:"number_of_cores,omitempty"`
	LogicalProcessors        int32                  `protobuf:"varint,7,opt,name=logical_processors,json=logicalProcessors,proto3" json:"logical_processors,omitempty"`
	AddressWidth             string                 `protobuf:"bytes,8,opt,name=address_width,json=addressWidth,proto3" json:"address_width,omitempty"`
	CurrentClockSpeed        int32                  `protobuf:"varint,9,opt,name=current_clock_speed,json=currentClockSpeed,proto3" json:"current_clock_speed,omitempty"`
	MaxClockSpeed            int32                  `protobuf:"varint,10,opt,name=max_clock_speed,json=maxClockSpeed,proto3" json:"max_clock_speed,omitempty"`
	SocketDesignation        string                 `protobuf:"bytes,11,opt,name=socket_designation,json=socketDesignation,proto3" json:"socket_designation,omitempty"`
	Availability             string                 `protobuf:"bytes,12,opt,name=availability,proto3" json:"availability,omitempty"`
	LoadPercentage           int32                  `protobuf:"varint,13,opt,name=load_percentage,json=loadPercentage,proto3" json:"load_percentage,omitempty"`
	NumberOfEfficiencyCores  int32                  `protobuf:"varint,14,opt,name=number_of_efficiency_cores,json=numberOfEfficiencyCores,proto3" json:"number_of_efficiency_cores,omitempty"`
	NumberOfPerformanceCores int32                  `protobuf:"varint,15,opt,name=number_of_performance_cores,json=numberOfPerformanceCores,proto3" json:"number_of_performance_cores,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CpuInfoRecord) Reset() {
	*x = CpuInfoRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfoRecord) ProtoMessage() {}

func (x *CpuInfoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfoRecord.ProtoReflect.Descriptor instead.
func (*CpuInfoRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{5}
}

func (x *CpuInfoRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CpuInfoRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CpuInfoRecord) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *CpuInfoRecord) GetProcessorType() string {
	if x != nil {
		return x.ProcessorType
	}
	return ""
}

func (x *CpuInfoRecord) GetCpuStatus() int32 {
	if x != nil {
		return x.CpuStatus
	}
	return 0
}

func (x *CpuInfoRecord) GetNumberOfCores() string {
	if x != nil {
		return x.NumberOfCores
	}
	return ""
}

func (x *CpuInfoRecord) GetLogicalProcessors() int32 {
	if x != nil {
		return x.LogicalProcessors
	}
	return 0
}

func (x *CpuInfoRecord) GetAddressWidth() string {
	if x != nil {
		return x.AddressWidth
	}
	return ""
}

func (x *CpuInfoRecord) GetCurrentClockSpeed() int32 {
	if x != nil {
		return x.CurrentClockSpeed
	}
	return 0
}

func (x *CpuInfoRecord) GetMaxClockSpeed() int32 {
	if x != nil {
		return x.MaxClockSpeed
	}
	return 0
}

func (x *CpuInfoRecord) GetSocketDesignation() string {
	if x != nil {
		return x.SocketDesignation
	}
	return ""
}

func (x *CpuInfoRecord) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *CpuInfoRecord) GetLoadPercentage() int32 {
	if x != nil {
		return x.LoadPercentage
	}
	return 0
}

func (x *CpuInfoRecord) GetNumberOfEfficiencyCores() int32 {
	if x != nil {
		return x.NumberOfEfficiencyCores
	}
	return 0
}

func (x *CpuInfoRecord) GetNumberOfPerformanceCores() int32 {
	if x != nil {
		return x.NumberOfPerformanceCores
	}
	return 0
}

type MemoryInfoRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MemoryTotal     int64                  `protobuf:"varint,1,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryFree      int64                  `protobuf:"varint,2,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	MemoryAvailable int64                  `protobuf:"varint,3,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	SwapTotal       int64                  `protobuf:"varint,4,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree        int64                  `protobuf:"varint,5,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryInfoRecord) Reset() {
	*x = MemoryInfoRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfoRecord) ProtoMessage() {}

func (x *MemoryInfoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfoRecord.ProtoReflect.Descriptor instead.
func (*MemoryInfoRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryInfoRecord) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MemoryInfoRecord) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *MemoryInfoRecord) GetMemoryAvailable() int64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *MemoryInfoRecord) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryInfoRecord) GetSwapFree() int64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

type DiskInfoRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*DiskInfoEntry       `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfoRecord) Reset() {
	*x = DiskInfoRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfoRecord) ProtoMessage() {}

func (x *DiskInfoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfoRecord.ProtoReflect.Descriptor instead.
func (*DiskInfoRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{7}
}

func (x *DiskInfoRecord) GetDisks() []*DiskInfoEntry {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskInfoEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	MountPoint     string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	FsType         string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	TotalBytes     int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes      int64                  `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,6,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	PercentUsed    float64                `protobuf:"fixed64,7,opt,name=percent_used,json=percentUsed,proto3" json:"percent_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiskInfoEntry) Reset() {
	*x = DiskInfoEntry{}
	mi := &file_AgentTelemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfoEntry) ProtoMessage() {}

func (x *DiskInfoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfoEntry.ProtoReflect.Descriptor instead.
func (*DiskInfoEntry) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{8}
}

func (x *DiskInfoEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskInfoEntry) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskInfoEntry) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskInfoEntry) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskInfoEntry) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskInfoEntry) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *DiskInfoEntry) GetPercentUsed() float64 {
	if x != nil {
		return x.PercentUsed
	}
	return 0
}

type CpuUtilizationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent int32                  `protobuf:"varint,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	UserTime        int32                  `protobuf:"varint,2,opt,name=user_time,json=userTime,proto3" json:"user_time,omitempty"`
	SystemTime      int32                  `protobuf:"varint,3,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`
	NiceTime        int32                  `protobuf:"varint,4,opt,name=nice_time,json=niceTime,proto3" json:"nice_time,omitempty"`
	IdleTime        int32                  `protobuf:"varint,5,opt,name=idle_time,json=idleTime,proto3" json:"idle_time,omitempty"`
	IowaitTime      int32                  `protobuf:"varint,6,opt,name=iowait_time,json=iowaitTime,proto3" json:"iowait_time,omitempty"`
	IrqTime         int32                  `protobuf:"varint,7,opt,name=irq_time,json=irqTime,proto3" json:"irq_time,omitempty"`
	SoftirqTime     int32                  `protobuf:"varint,8,opt,name=softirq_time,json=softirqTime,proto3" json:"softirq_time,omitempty"`
	StealTime       int32                  `protobuf:"varint,9,opt,name=steal_time,json=stealTime,proto3" json:"steal_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuUtilizationRecord) Reset() {
	*x = CpuUtilizationRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuUtilizationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuUtilizationRecord) ProtoMessage() {}

func (x *CpuUtilizationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuUtilizationRecord.ProtoReflect.Descriptor instead.
func (*CpuUtilizationRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{9}
}

func (x *CpuUtilizationRecord) GetCpuUsagePercent() int32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *CpuUtilizationRecord) GetUserTime() int32 {
	if x != nil {
		return x.UserTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetSystemTime() int32 {
	if x != nil {
		return x.SystemTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetNiceTime() int32 {
	if x != nil {
		return x.NiceTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetIdleTime() int32 {
	if x != nil {
		return x.IdleTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetIowaitTime() int32 {
	if x != nil {
		return x.IowaitTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetIrqTime() int32 {
	if x != nil {
		return x.IrqTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetSoftirqTime() int32 {
	if x != nil {
		return x.SoftirqTime
	}
	return 0
}

func (x *CpuUtilizationRecord) GetStealTime() int32 {
	if x != nil {
		return x.StealTime
	}
	return 0
}

type MemoryUtilizationRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemoryTotal        int64                  `protobuf:"varint,1,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryFree         int64                  `protobuf:"varint,2,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	MemoryUsed         int64                  `protobuf:"varint,3,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryUsagePercent int32                  `protobuf:"varint,4,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MemoryUtilizationRecord) Reset() {
	*x = MemoryUtilizationRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryUtilizationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryUtilizationRecord) ProtoMessage() {}

func (x *MemoryUtilizationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryUtilizationRecord.ProtoReflect.Descriptor instead.
func (*MemoryUtilizationRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{10}
}

func (x *MemoryUtilizationRecord) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MemoryUtilizationRecord) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *MemoryUtilizationRecord) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *MemoryUtilizationRecord) GetMemoryUsagePercent() int32 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

type DiskUtilizationRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Disks         []*DiskUtilizationEntry `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUtilizationRecord) Reset() {
	*x = DiskUtilizationRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUtilizationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUtilizationRecord) ProtoMessage() {}

func (x *DiskUtilizationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUtilizationRecord.ProtoReflect.Descriptor instead.
func (*DiskUtilizationRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{11}
}

func (x *DiskUtilizationRecord) GetDisks() []*DiskUtilizationEntry {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskUtilizationEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Device          string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	BlocksSize      int64                  `protobuf:"varint,3,opt,name=blocks_size,json=blocksSize,proto3" json:"blocks_size,omitempty"`
	Blocks          int64                  `protobuf:"varint,4,opt,name=blocks,proto3" json:"blocks,omitempty"`
	BlocksFree      int64                  `protobuf:"varint,5,opt,name=blocks_free,json=blocksFree,proto3" json:"blocks_free,omitempty"`
	BlocksAvailable int64                  `protobuf:"varint,6,opt,name=blocks_available,json=blocksAvailable,proto3" json:"blocks_available,omitempty"`
	BlocksUsed      int64                  `protobuf:"varint,7,opt,name=blocks_used,json=blocksUsed,proto3" json:"blocks_used,omitempty"`
	UsagePercent    int32                  `protobuf:"varint,8,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiskUtilizationEntry) Reset() {
	*x = DiskUtilizationEntry{}
	mi := &file_AgentTelemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUtilizationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUtilizationEntry) ProtoMessage() {}

func (x *DiskUtilizationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUtilizationEntry.ProtoReflect.Descriptor instead.
func (*DiskUtilizationEntry) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{12}
}

func (x *DiskUtilizationEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskUtilizationEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskUtilizationEntry) GetBlocksSize() int64 {
	if x != nil {
		return x.BlocksSize
	}
	return 0
}

func (x *DiskUtilizationEntry) GetBlocks() int64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *DiskUtilizationEntry) GetBlocksFree() int64 {
	if x != nil {
		return x.BlocksFree
	}
	return 0
}

func (x *DiskUtilizationEntry) GetBlocksAvailable() int64 {
	if x != nil {
		return x.BlocksAvailable
	}
	return 0
}

func (x *DiskUtilizationEntry) GetBlocksUsed() int64 {
	if x != nil {
		return x.BlocksUsed
	}
	return 0
}

func (x *DiskUtilizationEntry) GetUsagePercent() int32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type HardwareHealthRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Fans               []*FanReading          `protobuf:"bytes,1,rep,name=fans,proto3" json:"fans,omitempty"`
	PowerSupplies      []*PowerSupplyReading  `protobuf:"bytes,2,rep,name=power_supplies,json=powerSupplies,proto3" json:"power_supplies,omitempty"`
	Temperatures       []*TemperatureReading  `protobuf:"bytes,3,rep,name=temperatures,proto3" json:"temperatures,omitempty"`
	DiskSmart          []*DiskSmartReading    `protobuf:"bytes,4,rep,name=disk_smart,json=diskSmart,proto3" json:"disk_smart,omitempty"`
	BmcFirmwareVersion string                 `protobuf:"bytes,5,opt,name=bmc_firmware_version,json=bmcFirmwareVersion,proto3" json:"bmc_firmware_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HardwareHealthRecord) Reset() {
	*x = HardwareHealthRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareHealthRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareHealthRecord) ProtoMessage() {}

func (x *HardwareHealthRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareHealthRecord.ProtoReflect.Descriptor instead.
func (*HardwareHealthRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{13}
}

func (x *HardwareHealthRecord) GetFans() []*FanReading {
	if x != nil {
		return x.Fans
	}
	return nil
}

func (x *HardwareHealthRecord) GetPowerSupplies() []*PowerSupplyReading {
	if x != nil {
		return x.PowerSupplies
	}
	return nil
}

func (x *HardwareHealthRecord) GetTemperatures() []*TemperatureReading {
	if x != nil {
		return x.Temperatures
	}
	return nil
}

func (x *HardwareHealthRecord) GetDiskSmart() []*DiskSmartReading {
	if x != nil {
		return x.DiskSmart
	}
	return nil
}

func (x *HardwareHealthRecord) GetBmcFirmwareVersion() string {
	if x != nil {
		return x.BmcFirmwareVersion
	}
	return ""
}

type FanReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rpm           int32                  `protobuf:"varint,2,opt,name=rpm,proto3" json:"rpm,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanReading) Reset() {
	*x = FanReading{}
	mi := &file_AgentTelemetry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanReading) ProtoMessage() {}

func (x *FanReading) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanReading.ProtoReflect.Descriptor instead.
func (*FanReading) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{14}
}

func (x *FanReading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FanReading) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *FanReading) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PowerSupplyReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Watts         int32                  `protobuf:"varint,2,opt,name=watts,proto3" json:"watts,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerSupplyReading) Reset() {
	*x = PowerSupplyReading{}
	mi := &file_AgentTelemetry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerSupplyReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerSupplyReading) ProtoMessage() {}

func (x *PowerSupplyReading) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerSupplyReading.ProtoReflect.Descriptor instead.
func (*PowerSupplyReading) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{15}
}

func (x *PowerSupplyReading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PowerSupplyReading) GetWatts() int32 {
	if x != nil {
		return x.Watts
	}
	return 0
}

func (x *PowerSupplyReading) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TemperatureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Celsius       float64                `protobuf:"fixed64,2,opt,name=celsius,proto3" json:"celsius,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureReading) Reset() {
	*x = TemperatureReading{}
	mi := &file_AgentTelemetry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureReading) ProtoMessage() {}

func (x *TemperatureReading) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureReading.ProtoReflect.Descriptor instead.
func (*TemperatureReading) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{16}
}

func (x *TemperatureReading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemperatureReading) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *TemperatureReading) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DiskSmartReading struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Device             string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Model              string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	HealthStatus       string                 `protobuf:"bytes,3,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	TemperatureCelsius int32                  `protobuf:"varint,4,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	WearoutPercent     int32                  `protobuf:"varint,5,opt,name=wearout_percent,json=wearoutPercent,proto3" json:"wearout_percent,omitempty"`
	PowerOnHours       int64                  `protobuf:"varint,6,opt,name=power_on_hours,json=powerOnHours,proto3" json:"power_on_hours,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DiskSmartReading) Reset() {
	*x = DiskSmartReading{}
	mi := &file_AgentTelemetry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSmartReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSmartReading) ProtoMessage() {}

func (x *DiskSmartReading) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSmartReading.ProtoReflect.Descriptor instead.
func (*DiskSmartReading) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{17}
}

func (x *DiskSmartReading) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskSmartReading) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskSmartReading) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *DiskSmartReading) GetTemperatureCelsius() int32 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *DiskSmartReading) GetWearoutPercent() int32 {
	if x != nil {
		return x.WearoutPercent
	}
	return 0
}

func (x *DiskSmartReading) GetPowerOnHours() int64 {
	if x != nil {
		return x.PowerOnHours
	}
	return 0
}

type PackageUpdatesRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageManager string                 `protobuf:"bytes,1,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	Updates        []*PackageUpdate       `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PackageUpdatesRecord) Reset() {
	*x = PackageUpdatesRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageUpdatesRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageUpdatesRecord) ProtoMessage() {}

func (x *PackageUpdatesRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageUpdatesRecord.ProtoReflect.Descriptor instead.
func (*PackageUpdatesRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{18}
}

func (x *PackageUpdatesRecord) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *PackageUpdatesRecord) GetUpdates() []*PackageUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PackageUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CurrentVersion   string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	AvailableVersion string                 `protobuf:"bytes,3,opt,name=available_version,json=availableVersion,proto3" json:"available_version,omitempty"`
	IsSecurityUpdate bool                   `protobuf:"varint,4,opt,name=is_security_update,json=isSecurityUpdate,proto3" json:"is_security_update,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PackageUpdate) Reset() {
	*x = PackageUpdate{}
	mi := &file_AgentTelemetry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageUpdate) ProtoMessage() {}

func (x *PackageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageUpdate.ProtoReflect.Descriptor instead.
func (*PackageUpdate) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{19}
}

func (x *PackageUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageUpdate) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *PackageUpdate) GetAvailableVersion() string {
	if x != nil {
		return x.AvailableVersion
	}
	return ""
}

func (x *PackageUpdate) GetIsSecurityUpdate() bool {
	if x != nil {
		return x.IsSecurityUpdate
	}
	return false
}

type ServiceStatusRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceEntry        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusRecord) Reset() {
	*x = ServiceStatusRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusRecord) ProtoMessage() {}

func (x *ServiceStatusRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusRecord.ProtoReflect.Descriptor instead.
func (*ServiceStatusRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceStatusRecord) GetServices() []*ServiceEntry {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	LoadState     string                 `protobuf:"bytes,2,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	ActiveState   string                 `protobuf:"bytes,3,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	SubState      string                 `protobuf:"bytes,4,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_AgentTelemetry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{21}
}

func (x *ServiceEntry) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ServiceEntry) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *ServiceEntry) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *ServiceEntry) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *ServiceEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SshSessionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    int32                  `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	AuthMethod    string                 `protobuf:"bytes,5,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshSessionRecord) Reset() {
	*x = SshSessionRecord{}
	mi := &file_AgentTelemetry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshSessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshSessionRecord) ProtoMessage() {}

func (x *SshSessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_AgentTelemetry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshSessionRecord.ProtoReflect.Descriptor instead.
func (*SshSessionRecord) Descriptor() ([]byte, []int) {
	return file_AgentTelemetry_proto_rawDescGZIP(), []int{22}
}

func (x *SshSessionRecord) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SshSessionRecord) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *SshSessionRecord) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *SshSessionRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SshSessionRecord) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *SshSessionRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_AgentTelemetry_proto protoreflect.FileDescriptor

const file_AgentTelemetry_proto_rawDesc = "" +
	"\n" +
	"\x14AgentTelemetry.proto\x12\x05agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x11TelemetryEnvelope\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12C\n" +
	"\x0fagent_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eagentTimestamp\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.agent.TelemetryItemR\x05items\"\xae\a\n" +
	"\rTelemetryItem\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.agent.TelemetryTypesR\x04type\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12:\n" +
	"\vsystem_info\x18\n" +
	" \x01(\v2\x17.agent.SystemInfoRecordH\x00R\n" +
	"systemInfo\x127\n" +
	"\n" +
	"os_version\x18\v \x01(\v2\x16.agent.OsVersionRecordH\x00R\tosVersion\x121\n" +
	"\bcpu_info\x18\f \x01(\v2\x14.agent.CpuInfoRecordH\x00R\acpuInfo\x12:\n" +
	"\vmemory_info\x18\r \x01(\v2\x17.agent.MemoryInfoRecordH\x00R\n" +
	"memoryInfo\x124\n" +
	"\tdisk_info\x18\x0e \x01(\v2\x15.agent.DiskInfoRecordH\x00R\bdiskInfo\x12F\n" +
	"\x0fcpu_utilization\x18\x0f \x01(\v2\x1b.agent.CpuUtilizationRecordH\x00R\x0ecpuUtilization\x12O\n" +
	"\x12memory_utilization\x18\x10 \x01(\v2\x1e.agent.MemoryUtilizationRecordH\x00R\x11memoryUtilization\x12I\n" +
	"\x10disk_utilization\x18\x11 \x01(\v2\x1c.agent.DiskUtilizationRecordH\x00R\x0fdiskUtilization\x12:\n" +
	"\vssh_session\x18\x12 \x01(\v2\x17.agent.SshSessionRecordH\x00R\n" +
	"sshSession\x12F\n" +
	"\x0fhardware_health\x18\x13 \x01(\v2\x1b.agent.HardwareHealthRecordH\x00R\x0ehardwareHealth\x12F\n" +
	"\x0fpackage_updates\x18\x14 \x01(\v2\x1b.agent.PackageUpdatesRecordH\x00R\x0epackageUpdates\x12C\n" +
	"\x0eservice_status\x18\x15 \x01(\v2\x1a.agent.ServiceStatusRecordH\x00R\rserviceStatusB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\fTelemetryAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x124\n" +
	"\x16acknowledged_event_ids\x18\x02 \x03(\tR\x14acknowledgedEventIds\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xd8\x06\n" +
	"\x10SystemInfoRecord\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x19\n" +
	"\bcpu_type\x18\x03 \x01(\tR\acpuType\x12\x1f\n" +
	"\vcpu_subtype\x18\x04 \x01(\tR\n" +
	"cpuSubtype\x12\x1b\n" +
	"\tcpu_brand\x18\x05 \x01(\tR\bcpuBrand\x12,\n" +
	"\x12cpu_physical_cores\x18\x06 \x01(\x05R\x10cpuPhysicalCores\x12*\n" +
	"\x11cpu_logical_cores\x18\a \x01(\x05R\x0fcpuLogicalCores\x12#\n" +
	"\rcpu_microcode\x18\b \x01(\tR\fcpuMicrocode\x12'\n" +
	"\x0fphysical_memory\x18\t \x01(\x03R\x0ephysicalMemory\x12'\n" +
	"\x0fhardware_vendor\x18\n" +
	" \x01(\tR\x0ehardwareVendor\x12%\n" +
	"\x0ehardware_model\x18\v \x01(\tR\rhardwareModel\x12)\n" +
	"\x10hardware_version\x18\f \x01(\tR\x0fhardwareVersion\x12'\n" +
	"\x0fhardware_serial\x18\r \x01(\tR\x0ehardwareSerial\x12!\n" +
	"\fboard_vendor\x18\x0e \x01(\tR\vboardVendor\x12\x1f\n" +
	"\vboard_model\x18\x0f \x01(\tR\n" +
	"boardModel\x12#\n" +
	"\rboard_version\x18\x10 \x01(\tR\fboardVersion\x12!\n" +
	"\fboard_serial\x18\x11 \x01(\tR\vboardSerial\x12#\n" +
	"\rcomputer_name\x18\x12 \x01(\tR\fcomputerName\x12%\n" +
	"\x0elocal_hostname\x18\x13 \x01(\tR\rlocalHostname\x12*\n" +
	"\x11emulated_cpu_type\x18\x14 \x01(\tR\x0femulatedCpuType\x12%\n" +
	"\x0euptime_seconds\x18\x15 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fbios_version\x18\x16 \x01(\tR\vbiosVersion\x12!\n" +
	"\fip_addresses\x18\x17 \x03(\tR\vipAddresses\"\xd4\x02\n" +
	"\x0fOsVersionRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05major\x18\x03 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x04 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x05 \x01(\x05R\x05patch\x12\x14\n" +
	"\x05build\x18\x06 \x01(\tR\x05build\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12\x1a\n" +
	"\bcodename\x18\b \x01(\tR\bcodename\x12\x12\n" +
	"\x04arch\x18\t \x01(\tR\x04arch\x12\x14\n" +
	"\x05extra\x18\n" +
	" \x01(\tR\x05extra\x12=\n" +
	"\finstall_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vinstallDate\x12\x1a\n" +
	"\brevision\x18\f \x01(\tR\brevision\"\xf8\x04\n" +
	"\rCpuInfoRecord\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\x12%\n" +
	"\x0eprocessor_type\x18\x04 \x01(\tR\rprocessorType\x12\x1d\n" +
	"\n" +
	"cpu_status\x18\x05 \x01(\x05R\tcpuStatus\x12&\n" +
	"\x0fnumber_of_cores\x18\x06 \x01(\tR\rnumberOfCores\x12-\n" +
	"\x12logical_processors\x18\a \x01(\x05R\x11logicalProcessors\x12#\n" +
	"\raddress_width\x18\b \x01(\tR\faddressWidth\x12.\n" +
	"\x13current_clock_speed\x18\t \x01(\x05R\x11currentClockSpeed\x12&\n" +
	"\x0fmax_clock_speed\x18\n" +
	" \x01(\x05R\rmaxClockSpeed\x12-\n" +
	"\x12socket_designation\x18\v \x01(\tR\x11socketDesignation\x12\"\n" +
	"\favailability\x18\f \x01(\tR\favailability\x12'\n" +
	"\x0fload_percentage\x18\r \x01(\x05R\x0eloadPercentage\x12;\n" +
	"\x1anumber_of_efficiency_cores\x18\x0e \x01(\x05R\x17numberOfEfficiencyCores\x12=\n" +
	"\x1bnumber_of_performance_cores\x18\x0f \x01(\x05R\x18numberOfPerformanceCores\"\xbd\x01\n" +
	"\x10MemoryInfoRecord\x12!\n" +
	"\fmemory_total\x18\x01 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_free\x18\x02 \x01(\x03R\n" +
	"memoryFree\x12)\n" +
	"\x10memory_available\x18\x03 \x01(\x03R\x0fmemoryAvailable\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x04 \x01(\x03R\tswapTotal\x12\x1b\n" +
	"\tswap_free\x18\x05 \x01(\x03R\bswapFree\"<\n" +
	"\x0eDiskInfoRecord\x12*\n" +
	"\x05disks\x18\x01 \x03(\v2\x14.agent.DiskInfoEntryR\x05disks\"\xed\x01\n" +
	"\rDiskInfoEntry\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x03R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x06 \x01(\x03R\x0eavailableBytes\x12!\n" +
	"\fpercent_used\x18\a \x01(\x01R\vpercentUsed\"\xb8\x02\n" +
	"\x14CpuUtilizationRecord\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x05R\x0fcpuUsagePercent\x12\x1b\n" +
	"\tuser_time\x18\x02 \x01(\x05R\buserTime\x12\x1f\n" +
	"\vsystem_time\x18\x03 \x01(\x05R\n" +
	"systemTime\x12\x1b\n" +
	"\tnice_time\x18\x04 \x01(\x05R\bniceTime\x12\x1b\n" +
	"\tidle_time\x18\x05 \x01(\x05R\bidleTime\x12\x1f\n" +
	"\viowait_time\x18\x06 \x01(\x05R\n" +
	"iowaitTime\x12\x19\n" +
	"\birq_time\x18\a \x01(\x05R\airqTime\x12!\n" +
	"\fsoftirq_time\x18\b \x01(\x05R\vsoftirqTime\x12\x1d\n" +
	"\n" +
	"steal_time\x18\t \x01(\x05R\tstealTime\"\xb0\x01\n" +
	"\x17MemoryUtilizationRecord\x12!\n" +
	"\fmemory_total\x18\x01 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_free\x18\x02 \x01(\x03R\n" +
	"memoryFree\x12\x1f\n" +
	"\vmemory_used\x18\x03 \x01(\x03R\n" +
	"memoryUsed\x120\n" +
	"\x14memory_usage_percent\x18\x04 \x01(\x05R\x12memoryUsagePercent\"J\n" +
	"\x15DiskUtilizationRecord\x121\n" +
	"\x05disks\x18\x01 \x03(\v2\x1b.agent.DiskUtilizationEntryR\x05disks\"\x8d\x02\n" +
	"\x14DiskUtilizationEntry\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vblocks_size\x18\x03 \x01(\x03R\n" +
	"blocksSize\x12\x16\n" +
	"\x06blocks\x18\x04 \x01(\x03R\x06blocks\x12\x1f\n" +
	"\vblocks_free\x18\x05 \x01(\x03R\n" +
	"blocksFree\x12)\n" +
	"\x10blocks_available\x18\x06 \x01(\x03R\x0fblocksAvailable\x12\x1f\n" +
	"\vblocks_used\x18\a \x01(\x03R\n" +
	"blocksUsed\x12#\n" +
	"\rusage_percent\x18\b \x01(\x05R\fusagePercent\"\xa8\x02\n" +
	"\x14HardwareHealthRecord\x12%\n" +
	"\x04fans\x18\x01 \x03(\v2\x11.agent.FanReadingR\x04fans\x12@\n" +
	"\x0epower_supplies\x18\x02 \x03(\v2\x19.agent.PowerSupplyReadingR\rpowerSupplies\x12=\n" +
	"\ftemperatures\x18\x03 \x03(\v2\x19.agent.TemperatureReadingR\ftemperatures\x126\n" +
	"\n" +
	"disk_smart\x18\x04 \x03(\v2\x17.agent.DiskSmartReadingR\tdiskSmart\x120\n" +
	"\x14bmc_firmware_version\x18\x05 \x01(\tR\x12bmcFirmwareVersion\"J\n" +
	"\n" +
	"FanReading\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03rpm\x18\x02 \x01(\x05R\x03rpm\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"V\n" +
	"\x12PowerSupplyReading\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05watts\x18\x02 \x01(\x05R\x05watts\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Z\n" +
	"\x12TemperatureReading\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acelsius\x18\x02 \x01(\x01R\acelsius\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xe5\x01\n" +
	"\x10DiskSmartReading\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rhealth_status\x18\x03 \x01(\tR\fhealthStatus\x12/\n" +
	"\x13temperature_celsius\x18\x04 \x01(\x05R\x12temperatureCelsius\x12'\n" +
	"\x0fwearout_percent\x18\x05 \x01(\x05R\x0ewearoutPercent\x12$\n" +
	"\x0epower_on_hours\x18\x06 \x01(\x03R\fpowerOnHours\"o\n" +
	"\x14PackageUpdatesRecord\x12'\n" +
	"\x0fpackage_manager\x18\x01 \x01(\tR\x0epackageManager\x12.\n" +
	"\aupdates\x18\x02 \x03(\v2\x14.agent.PackageUpdateR\aupdates\"\xa7\x01\n" +
	"\rPackageUpdate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\x12+\n" +
	"\x11available_version\x18\x03 \x01(\tR\x10availableVersion\x12,\n" +
	"\x12is_security_update\x18\x04 \x01(\bR\x10isSecurityUpdate\"F\n" +
	"\x13ServiceStatusRecord\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.agent.ServiceEntryR\bservices\"\xa3\x01\n" +
	"\fServiceEntry\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"load_state\x18\x02 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x03 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x04 \x01(\tR\bsubState\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xbb\x01\n" +
	"\x10SshSessionRecord\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\x05R\n" +
	"sourcePort\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vauth_method\x18\x05 \x01(\tR\n" +
	"authMethod\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp*\xc4\x02\n" +
	"\x0eTelemetryTypes\x12\x15\n" +
	"\x11TELEMETRY_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SYSTEM_INFO_TYPE\x10\x01\x12\x13\n" +
	"\x0fOS_VERSION_TYPE\x10\x02\x12\x11\n" +
	"\rCPU_INFO_TYPE\x10\x03\x12\x14\n" +
	"\x10MEMORY_INFO_TYPE\x10\x04\x12\x12\n" +
	"\x0eDISK_INFO_TYPE\x10\x05\x12\x18\n" +
	"\x14CPU_UTILIZATION_TYPE\x10\x06\x12\x1b\n" +
	"\x17MEMORY_UTILIZATION_TYPE\x10\a\x12\x19\n" +
	"\x15DISK_UTILIZATION_TYPE\x10\b\x12\x14\n" +
	"\x10SSH_SESSION_TYPE\x10\t\x12\x18\n" +
	"\x14HARDWARE_HEALTH_TYPE\x10\n" +
	"\x12\x18\n" +
	"\x14PACKAGE_UPDATES_TYPE\x10\v\x12\x17\n" +
	"\x13SERVICE_STATUS_TYPE\x10\f2\x93\x01\n" +
	"\tTelemetry\x12D\n" +
	"\x0fStreamTelemetry\x12\x18.agent.TelemetryEnvelope\x1a\x13.agent.TelemetryAck(\x010\x01\x12@\n" +
	"\x0fSubmitTelemetry\x12\x18.agent.TelemetryEnvelope\x1a\x13.agent.TelemetryAckB\\Z,github.com/framlux/vord/internal/proto/agent\xaa\x02+Framlux.FleetManagement.Grpc.AgentTelemetryb\x06proto3"

var (
	file_AgentTelemetry_proto_rawDescOnce sync.Once
	file_AgentTelemetry_proto_rawDescData []byte
)

func file_AgentTelemetry_proto_rawDescGZIP() []byte {
	file_AgentTelemetry_proto_rawDescOnce.Do(func() {
		file_AgentTelemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AgentTelemetry_proto_rawDesc), len(file_AgentTelemetry_proto_rawDesc)))
	})
	return file_AgentTelemetry_proto_rawDescData
}

var file_AgentTelemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AgentTelemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_AgentTelemetry_proto_goTypes = []any{
	(TelemetryTypes)(0),             // 0: agent.TelemetryTypes
	(*TelemetryEnvelope)(nil),       // 1: agent.TelemetryEnvelope
	(*TelemetryItem)(nil),           // 2: agent.TelemetryItem
	(*TelemetryAck)(nil),            // 3: agent.TelemetryAck
	(*SystemInfoRecord)(nil),        // 4: agent.SystemInfoRecord
	(*OsVersionRecord)(nil),         // 5: agent.OsVersionRecord
	(*CpuInfoRecord)(nil),           // 6: agent.CpuInfoRecord
	(*MemoryInfoRecord)(nil),        // 7: agent.MemoryInfoRecord
	(*DiskInfoRecord)(nil),          // 8: agent.DiskInfoRecord
	(*DiskInfoEntry)(nil),           // 9: agent.DiskInfoEntry
	(*CpuUtilizationRecord)(nil),    // 10: agent.CpuUtilizationRecord
	(*MemoryUtilizationRecord)(nil), // 11: agent.MemoryUtilizationRecord
	(*DiskUtilizationRecord)(nil),   // 12: agent.DiskUtilizationRecord
	(*DiskUtilizationEntry)(nil),    // 13: agent.DiskUtilizationEntry
	(*HardwareHealthRecord)(nil),    // 14: agent.HardwareHealthRecord
	(*FanReading)(nil),              // 15: agent.FanReading
	(*PowerSupplyReading)(nil),      // 16: agent.PowerSupplyReading
	(*TemperatureReading)(nil),      // 17: agent.TemperatureReading
	(*DiskSmartReading)(nil),        // 18: agent.DiskSmartReading
	(*PackageUpdatesRecord)(nil),    // 19: agent.PackageUpdatesRecord
	(*PackageUpdate)(nil),           // 20: agent.PackageUpdate
	(*ServiceStatusRecord)(nil),     // 21: agent.ServiceStatusRecord
	(*ServiceEntry)(nil),            // 22: agent.ServiceEntry
	(*SshSessionRecord)(nil),        // 23: agent.SshSessionRecord
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
}
var file_AgentTelemetry_proto_depIdxs = []int32{
	24, // 0: agent.TelemetryEnvelope.agent_timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: agent.TelemetryEnvelope.items:type_name -> agent.TelemetryItem
	0,  // 2: agent.TelemetryItem.type:type_name -> agent.TelemetryTypes
	24, // 3: agent.TelemetryItem.collected_at:type_name -> google.protobuf.Timestamp
	4,  // 4: agent.TelemetryItem.system_info:type_name -> agent.SystemInfoRecord
	5,  // 5: agent.TelemetryItem.os_version:type_name -> agent.OsVersionRecord
	6,  // 6: agent.TelemetryItem.cpu_info:type_name -> agent.CpuInfoRecord
	7,  // 7: agent.TelemetryItem.memory_info:type_name -> agent.MemoryInfoRecord
	8,  // 8: agent.TelemetryItem.disk_info:type_name -> agent.DiskInfoRecord
	10, // 9: agent.TelemetryItem.cpu_utilization:type_name -> agent.CpuUtilizationRecord
	11, // 10: agent.TelemetryItem.memory_utilization:type_name -> agent.MemoryUtilizationRecord
	12, // 11: agent.TelemetryItem.disk_utilization:type_name -> agent.DiskUtilizationRecord
	23, // 12: agent.TelemetryItem.ssh_session:type_name -> agent.SshSessionRecord
	14, // 13: agent.TelemetryItem.hardware_health:type_name -> agent.HardwareHealthRecord
	19, // 14: agent.TelemetryItem.package_updates:type_name -> agent.PackageUpdatesRecord
	21, // 15: agent.TelemetryItem.service_status:type_name -> agent.ServiceStatusRecord
	24, // 16: agent.OsVersionRecord.install_date:type_name -> google.protobuf.Timestamp
	9,  // 17: agent.DiskInfoRecord.disks:type_name -> agent.DiskInfoEntry
	13, // 18: agent.DiskUtilizationRecord.disks:type_name -> agent.DiskUtilizationEntry
	15, // 19: agent.HardwareHealthRecord.fans:type_name -> agent.FanReading
	16, // 20: agent.HardwareHealthRecord.power_supplies:type_name -> agent.PowerSupplyReading
	17, // 21: agent.HardwareHealthRecord.temperatures:type_name -> agent.TemperatureReading
	18, // 22: agent.HardwareHealthRecord.disk_smart:type_name -> agent.DiskSmartReading
	20, // 23: agent.PackageUpdatesRecord.updates:type_name -> agent.PackageUpdate
	22, // 24: agent.ServiceStatusRecord.services:type_name -> agent.ServiceEntry
	1,  // 25: agent.Telemetry.StreamTelemetry:input_type -> agent.TelemetryEnvelope
	1,  // 26: agent.Telemetry.SubmitTelemetry:input_type -> agent.TelemetryEnvelope
	3,  // 27: agent.Telemetry.StreamTelemetry:output_type -> agent.TelemetryAck
	3,  // 28: agent.Telemetry.SubmitTelemetry:output_type -> agent.TelemetryAck
	27, // [27:29] is the sub-list for method output_type
	25, // [25:27] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_AgentTelemetry_proto_init() }
func file_AgentTelemetry_proto_init() {
	if File_AgentTelemetry_proto != nil {
		return
	}
	file_AgentTelemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*TelemetryItem_SystemInfo)(nil),
		(*TelemetryItem_OsVersion)(nil),
		(*TelemetryItem_CpuInfo)(nil),
		(*TelemetryItem_MemoryInfo)(nil),
		(*TelemetryItem_DiskInfo)(nil),
		(*TelemetryItem_CpuUtilization)(nil),
		(*TelemetryItem_MemoryUtilization)(nil),
		(*TelemetryItem_DiskUtilization)(nil),
		(*TelemetryItem_SshSession)(nil),
		(*TelemetryItem_HardwareHealth)(nil),
		(*TelemetryItem_PackageUpdates)(nil),
		(*TelemetryItem_ServiceStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AgentTelemetry_proto_rawDesc), len(file_AgentTelemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AgentTelemetry_proto_goTypes,
		DependencyIndexes: file_AgentTelemetry_proto_depIdxs,
		EnumInfos:         file_AgentTelemetry_proto_enumTypes,
		MessageInfos:      file_AgentTelemetry_proto_msgTypes,
	}.Build()
	File_AgentTelemetry_proto = out.File
	file_AgentTelemetry_proto_goTypes = nil
	file_AgentTelemetry_proto_depIdxs = nil
}
