// Copyright (c) 2026 Framlux LLC
// Licensed under the Functional Source License, Version 1.1, ALv2 Future License
// See LICENSE for details.

import { describe, it, expect } from 'vitest';
import { generateInstallScript } from './install-script';

describe('generateInstallScript', () => {
    it('should start with bash shebang', () => {
        const script = generateInstallScript('test-token-123');
        expect(script.startsWith('#!/usr/bin/env bash')).toBe(true);
    });

    it('should include PATH normalization for minimal environments', () => {
        const script = generateInstallScript('test-token');
        expect(script).toContain(
            'export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH}"'
        );
    });

    it('should contain the provided token value', () => {
        const script = generateInstallScript('my-secret-token-abc');
        expect(script).toContain('REGISTRATION_TOKEN="my-secret-token-abc"');
    });

    it('should contain the provided server address', () => {
        const script = generateInstallScript('token', 'custom.server.dev');
        expect(script).toContain('SERVER_ADDRESS="custom.server.dev"');
    });

    it('should use default server address when not provided', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('SERVER_ADDRESS="grpc.app.vordfleet.dev"');
    });

    it('should use default port when not provided', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('server_port = 443');
    });

    it('should use custom port when provided', () => {
        const script = generateInstallScript('token', 'grpc.app.vordfleet.dev', 12234);
        expect(script).toContain('server_port = 12234');
    });

    it('should not contain interactive read prompts', () => {
        const script = generateInstallScript('token');
        expect(script).not.toContain('read -r');
        expect(script).not.toContain('Enter the server address');
        expect(script).not.toContain('Enter your registration token');
    });

    it('should contain systemctl enable and start commands', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('systemctl enable');
        expect(script).toContain('systemctl start');
    });

    it('should contain config file write section', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('Writing configuration');
        expect(script).toContain('CONFIG_FILE');
        expect(script).toContain('chmod 0600');
    });

    it('should contain package installation', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('vord-agent');
        expect(script).toContain('apt-get install');
    });

    it('should escape double quotes in token values', () => {
        const script = generateInstallScript('token"with"quotes');
        expect(script).toContain('REGISTRATION_TOKEN="token\\"with\\"quotes"');
    });

    it('should escape dollar signs in token values', () => {
        const script = generateInstallScript('token$var');
        expect(script).toContain('REGISTRATION_TOKEN="token\\$var"');
    });

    it('should escape backslashes in token values', () => {
        const script = generateInstallScript('token\\slash');
        expect(script).toContain('REGISTRATION_TOKEN="token\\\\slash"');
    });

    it('should escape backticks in token values', () => {
        const script = generateInstallScript('token`cmd`end');
        expect(script).toContain('REGISTRATION_TOKEN="token\\`cmd\\`end"');
    });

    it('should escape shell-dangerous characters in server address', () => {
        const script = generateInstallScript('token', 'server"$`\\bad');
        expect(script).toContain('SERVER_ADDRESS="server\\"\\$\\`\\\\bad"');
    });

    it('should include use_tls setting', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('use_tls = true');
    });

    it('should include generated-by comment', () => {
        const script = generateInstallScript('token');
        expect(script).toContain('Generated by the Vord Fleet dashboard');
    });
});
