// Copyright (c) 2026 Framlux LLC
// Licensed under the Functional Source License, Version 1.1, ALv2 Future License
// See LICENSE for details.

// The canonical installer, imported verbatim at build time. The dashboard used to carry its own
// near-copy of this script, which drifted: it kept an unsigned-RPM gpgcheck, a `gpg --dearmor`
// that fails on any re-run, and a `systemctl start` against a unit the package had already
// started. Only one script body exists now, so a fix to deployment/agent/install.sh reaches the
// dashboard automatically and the CI drift guard covers this path too.
import canonicalInstaller from '../../../../../deployment/agent/install.sh?raw';

/**
 * Escapes a string value for safe inclusion inside double-quoted shell strings.
 * Prevents injection via characters that have special meaning in bash double quotes.
 */
function shellEscape(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\$/g, '\\$')
        .replace(/`/g, '\\`');
}

/**
 * Generates a pre-configured install script for the Vord Agent with the registration
 * token and server address already embedded. The generated script requires no
 * interactive input and can be pasted directly onto target machines.
 *
 * The output is a short prelude that exports the VORD_* variables the canonical installer already
 * reads, followed by that installer unchanged. Exporting a token is what puts the installer into
 * its non-interactive mode, so the prompts in the body are never reached.
 */
export function generateInstallScript(
    token: string,
    serverAddress: string = 'grpc.app.vordfleet.dev',
    serverPort: number = 443
): string {
    const escapedToken = shellEscape(token);
    const escapedServer = shellEscape(serverAddress);

    const prelude = `#!/usr/bin/env bash
# Copyright (c) 2026 Framlux LLC
# Licensed under the MIT License
# See LICENSE for details.
#
# Vord Agent installer — pre-configured with registration token and server address.
# Generated by the Vord Fleet dashboard.
# Usage: sudo bash install.sh
#
# Everything below the prelude is the canonical installer, byte-for-byte. Supplying a token here
# is what selects its non-interactive path, so it never prompts.

export VORD_REGISTRATION_TOKEN="${escapedToken}"
export VORD_SERVER_ADDRESS="${escapedServer}"
export VORD_SERVER_PORT=${serverPort}

`;

    return prelude + canonicalInstaller;
}
