// Copyright (c) 2026 Framlux LLC
// Licensed under the Functional Source License, Version 1.1, ALv2 Future License
// See LICENSE for details.

/**
 * Escapes a string value for safe inclusion inside double-quoted shell strings.
 * Prevents injection via characters that have special meaning in bash double quotes.
 */
function shellEscape(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\$/g, '\\$')
        .replace(/`/g, '\\`');
}

/**
 * Generates a pre-configured install script for the Vord Agent with the registration
 * token and server address already embedded. The generated script requires no
 * interactive input and can be pasted directly onto target machines.
 */
export function generateInstallScript(
    token: string,
    serverAddress: string = 'grpc.app.vordfleet.dev',
    serverPort: number = 443
): string {
    const escapedToken = shellEscape(token);
    const escapedServer = shellEscape(serverAddress);

    return `#!/usr/bin/env bash
# Copyright (c) 2026 Framlux LLC
# Licensed under the MIT License
# See LICENSE for details.
#
# Vord Agent installer — pre-configured with registration token and server address.
# Generated by the Vord Fleet dashboard.
# Usage: sudo bash install.sh

set -euo pipefail

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\${PATH}"

GPG_KEY_URL="https://apt.fury.io/framlux/gpg.key"
APT_REPO_URL="https://packages.framlux.io/apt/"
YUM_REPO_URL="https://packages.framlux.io/yum/"
PACKAGE_NAME="vord-agent"
CONFIG_DIR="/etc/framlux"
CONFIG_FILE="\${CONFIG_DIR}/vord-agent.toml"

# --- Helpers ---

info() {
    printf "\\033[1;34m==>\\033[0m %s\\n" "$1"
}

success() {
    printf "\\033[1;32m==>\\033[0m %s\\n" "$1"
}

error() {
    printf "\\033[1;31mERROR:\\033[0m %s\\n" "$1" >&2
}

# --- Preflight Checks ---

if [ "\${EUID:-$(id -u)}" -ne 0 ]; then
    error "This script must be run as root. Try: sudo bash install.sh"
    exit 1
fi

PKG_MANAGER=""
if command -v apt-get >/dev/null 2>&1; then
    PKG_MANAGER="apt"
elif command -v dnf >/dev/null 2>&1; then
    PKG_MANAGER="dnf"
elif command -v yum >/dev/null 2>&1; then
    PKG_MANAGER="yum"
else
    error "Unsupported system: neither apt-get, dnf, nor yum found."
    exit 1
fi

info "Detected package manager: \${PKG_MANAGER}"

# --- Import GPG Key ---

info "Importing Framlux GPG key..."

if [ "\${PKG_MANAGER}" = "apt" ]; then
    curl -fsSL "\${GPG_KEY_URL}" | apt-key add -
else
    rpm --import "\${GPG_KEY_URL}"
fi

# --- Add Package Repository ---

info "Adding Framlux package repository..."

if [ "\${PKG_MANAGER}" = "apt" ]; then
    cat > /etc/apt/sources.list.d/framlux.list <<EOF
deb \${APT_REPO_URL} * *
EOF
else
    cat > /etc/yum.repos.d/framlux.repo <<EOF
[framlux]
name=Framlux Packages
baseurl=\${YUM_REPO_URL}
enabled=1
gpgcheck=1
gpgkey=\${GPG_KEY_URL}
EOF
fi

# --- Update Package Cache ---

info "Updating package cache..."

if [ "\${PKG_MANAGER}" = "apt" ]; then
    apt-get update -qq
else
    \${PKG_MANAGER} makecache -q
fi

# --- Install the Agent ---

info "Installing \${PACKAGE_NAME}..."

if [ "\${PKG_MANAGER}" = "apt" ]; then
    apt-get install -y -qq "\${PACKAGE_NAME}"
else
    \${PKG_MANAGER} install -y -q "\${PACKAGE_NAME}"
fi

success "\${PACKAGE_NAME} installed successfully."

# --- Pre-configured values (generated by Vord Fleet dashboard) ---

SERVER_ADDRESS="${escapedServer}"
REGISTRATION_TOKEN="${escapedToken}"

# --- Write Configuration ---

info "Writing configuration to \${CONFIG_FILE}..."

mkdir -p "\${CONFIG_DIR}"
cat > "\${CONFIG_FILE}" <<EOF
server_address = "\${SERVER_ADDRESS}"
server_port = ${serverPort}
use_tls = true
registration_token = "\${REGISTRATION_TOKEN}"
EOF
chmod 0600 "\${CONFIG_FILE}"

# --- Create Data Directory ---

info "Creating data directory..."
mkdir -p /var/lib/vord-agent
chmod 0750 /var/lib/vord-agent

# --- Enable and Start the Agent ---

info "Enabling and starting \${PACKAGE_NAME}..."

systemctl enable "\${PACKAGE_NAME}"
systemctl start "\${PACKAGE_NAME}"

printf "\\n"
success "Vord Agent is installed and running!"
printf "\\n"
systemctl status "\${PACKAGE_NAME}" --no-pager
`;
}
