// Copyright (c) 2026 Framlux LLC
// Licensed under the Functional Source License, Version 1.1, ALv2 Future License
// See LICENSE for details.

import type { FleetMachineDto, PaginatedFleetOverviewDto } from '../types';
import { MachineHealthStatus } from '../types';
import { daysAgo, secondsAgo } from './time';

// Source of truth for fleet rows on the dashboard. Mix of bare-metal (prod LAN),
// rented dedicated (Hetzner / OVH), VMs, and one-off boxes — reinforces the
// "Linux servers you actually run yourself" positioning of the marketing copy.
const fleetMachines: FleetMachineDto[] = [
	{
		id: 1,
		name: 'web-01',
		hostname: 'web-01.prod.lan',
		ipAddress: '10.0.1.11',
		hardwareModel: 'Dell PowerEdge R740',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 23,
		memoryUsagePercent: 41,
		maxDiskUsagePercent: 38,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(12),
		pendingUpdates: 3,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 84
	},
	{
		id: 2,
		name: 'web-02',
		hostname: 'web-02.prod.lan',
		ipAddress: '10.0.1.12',
		hardwareModel: 'Dell PowerEdge R740',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 19,
		memoryUsagePercent: 38,
		maxDiskUsagePercent: 41,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(8),
		pendingUpdates: 3,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 84
	},
	{
		id: 3,
		name: 'db-primary',
		hostname: 'db-primary.prod.lan',
		ipAddress: '10.0.1.21',
		hardwareModel: 'Supermicro AS-2024US-TRT',
		healthStatus: MachineHealthStatus.Warning,
		cpuUsagePercent: 67,
		memoryUsagePercent: 78,
		maxDiskUsagePercent: 84,
		hasDiskHealthIssue: true,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(4),
		pendingUpdates: 0,
		securityUpdates: 2,
		failedServices: 0,
		totalServices: 92
	},
	{
		id: 4,
		name: 'db-replica-1',
		hostname: 'db-replica-1.prod.lan',
		ipAddress: '10.0.1.22',
		hardwareModel: 'Supermicro AS-2024US-TRT',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 31,
		memoryUsagePercent: 52,
		maxDiskUsagePercent: 79,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(6),
		pendingUpdates: 0,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 92
	},
	{
		id: 5,
		name: 'cache-01',
		hostname: 'cache-01.iad',
		ipAddress: '10.0.1.31',
		hardwareModel: 'HPE ProLiant DL380 Gen10',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 12,
		memoryUsagePercent: 67,
		maxDiskUsagePercent: 22,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(9),
		pendingUpdates: 5,
		securityUpdates: 1,
		failedServices: 0,
		totalServices: 76
	},
	{
		id: 6,
		name: 'cache-02',
		hostname: 'cache-02.iad',
		ipAddress: '10.0.1.32',
		hardwareModel: 'HPE ProLiant DL380 Gen10',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 14,
		memoryUsagePercent: 71,
		maxDiskUsagePercent: 24,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(11),
		pendingUpdates: 5,
		securityUpdates: 1,
		failedServices: 0,
		totalServices: 76
	},
	{
		id: 7,
		name: 'hetzner-fsn1-42',
		hostname: 'hetzner-fsn1-42',
		ipAddress: '195.201.34.42',
		hardwareModel: 'Hetzner AX52',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 28,
		memoryUsagePercent: 49,
		maxDiskUsagePercent: 51,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(15),
		pendingUpdates: 8,
		securityUpdates: 2,
		failedServices: 0,
		totalServices: 81
	},
	{
		id: 8,
		name: 'hetzner-fsn1-43',
		hostname: 'hetzner-fsn1-43',
		ipAddress: '195.201.34.43',
		hardwareModel: 'Hetzner AX52',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 26,
		memoryUsagePercent: 51,
		maxDiskUsagePercent: 53,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(13),
		pendingUpdates: 8,
		securityUpdates: 2,
		failedServices: 0,
		totalServices: 81
	},
	{
		id: 9,
		name: 'ovh-bhs5-12',
		hostname: 'ovh-bhs5-12',
		ipAddress: '158.69.121.12',
		hardwareModel: 'OVH Rise-1',
		healthStatus: MachineHealthStatus.Critical,
		cpuUsagePercent: 38,
		memoryUsagePercent: 44,
		maxDiskUsagePercent: 56,
		hasDiskHealthIssue: false,
		hasHardwareIssue: true,
		isOnline: true,
		lastPing: secondsAgo(21),
		pendingUpdates: 0,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 79
	},
	{
		id: 10,
		name: 'ovh-bhs5-13',
		hostname: 'ovh-bhs5-13',
		ipAddress: '158.69.121.13',
		hardwareModel: 'OVH Rise-1',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 41,
		memoryUsagePercent: 62,
		maxDiskUsagePercent: 48,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(7),
		pendingUpdates: 12,
		securityUpdates: 4,
		failedServices: 0,
		totalServices: 79
	},
	{
		id: 11,
		name: 'ci-runner-01',
		hostname: 'ci-runner-01',
		ipAddress: '10.0.2.11',
		hardwareModel: 'Whitebox (AMD EPYC 9554)',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 8,
		memoryUsagePercent: 22,
		maxDiskUsagePercent: 67,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(22),
		pendingUpdates: 14,
		securityUpdates: 3,
		failedServices: 1,
		totalServices: 68
	},
	{
		id: 12,
		name: 'ci-runner-02',
		hostname: 'ci-runner-02',
		ipAddress: '10.0.2.12',
		hardwareModel: 'Whitebox (AMD EPYC 9554)',
		healthStatus: MachineHealthStatus.Warning,
		cpuUsagePercent: 89,
		memoryUsagePercent: 92,
		maxDiskUsagePercent: 71,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(3),
		pendingUpdates: 14,
		securityUpdates: 3,
		failedServices: 0,
		totalServices: 68
	},
	{
		id: 13,
		name: 'vm-monitor',
		hostname: 'vm-monitor.k8s.lan',
		ipAddress: '10.0.3.21',
		hardwareModel: 'VMware ESXi VM (8 vCPU)',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 5,
		memoryUsagePercent: 34,
		maxDiskUsagePercent: 19,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(18),
		pendingUpdates: 1,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 54
	},
	{
		id: 14,
		name: 'vm-logs',
		hostname: 'vm-logs.k8s.lan',
		ipAddress: '10.0.3.22',
		hardwareModel: 'VMware ESXi VM (16 vCPU)',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 17,
		memoryUsagePercent: 58,
		maxDiskUsagePercent: 73,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(14),
		pendingUpdates: 1,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 54
	},
	{
		id: 15,
		name: 'vm-gateway',
		hostname: 'vm-gateway.k8s.lan',
		ipAddress: '10.0.3.23',
		hardwareModel: 'VMware ESXi VM (4 vCPU)',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 9,
		memoryUsagePercent: 41,
		maxDiskUsagePercent: 28,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(20),
		pendingUpdates: 1,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 54
	},
	{
		id: 16,
		name: 'gpu-trainer-01',
		hostname: 'gpu-trainer-01',
		ipAddress: '10.0.4.11',
		hardwareModel: 'Supermicro AS-8125GS-TNHR',
		healthStatus: MachineHealthStatus.Warning,
		cpuUsagePercent: 94,
		memoryUsagePercent: 81,
		maxDiskUsagePercent: 62,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(5),
		pendingUpdates: 0,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 71
	},
	{
		id: 17,
		name: 'nas-01',
		hostname: 'nas-01.home.lan',
		ipAddress: '10.0.5.11',
		hardwareModel: 'TrueNAS Mini X+',
		healthStatus: MachineHealthStatus.Offline,
		cpuUsagePercent: null,
		memoryUsagePercent: null,
		maxDiskUsagePercent: null,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: false,
		lastPing: daysAgo(2),
		pendingUpdates: 0,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 0
	},
	{
		id: 18,
		name: 'dev-shared',
		hostname: 'dev-shared.lan',
		ipAddress: '10.0.6.11',
		hardwareModel: 'System76 Thelio Mira',
		healthStatus: MachineHealthStatus.Healthy,
		cpuUsagePercent: 11,
		memoryUsagePercent: 28,
		maxDiskUsagePercent: 33,
		hasDiskHealthIssue: false,
		hasHardwareIssue: false,
		isOnline: true,
		lastPing: secondsAgo(28),
		pendingUpdates: 2,
		securityUpdates: 0,
		failedServices: 0,
		totalServices: 88
	}
];

export const mockFleetMachines: ReadonlyArray<FleetMachineDto> = fleetMachines;

export const mockFleetOverview: PaginatedFleetOverviewDto = {
	summary: {
		totalMachines: 18,
		onlineMachines: 17,
		offlineCount: 1,
		warningCount: 3,
		criticalCount: 1,
		securityUpdates: 18
	},
	machines: fleetMachines,
	page: 1,
	pageSize: 25,
	totalCount: 18,
	totalPages: 1
};
